### ISSUE TITLE
Introduce route lazy loading

### ISSUE THREAD

**Issue by wchrapka** [kyma-project/busola#1006]
**Description**
Lighthouse report shows that our bundle sizes are becoming a problem. Let's modify the application routing and lazy load the list, create and details components to not load all the scripts during the initial load.

**Reasons**
Too long script evaluation time

**Acceptance Criteria**

- [x] Routes are loaded with React.lazy
- [x] Suspense component hands the loading following the project styles

**Comment by valentinvieriu** [comment]
One important target is Cluster Overview page. We should focus on loading only the needed components for Cluster Overview
