### ISSUE TITLE
Backend doesn't access packages from the main repo in CI

### ISSUE THREAD

**Issue by wchrapka** [kyma-project/busola#1028]
**Description**
During the CI build, contrary to local build, Backend doesn't pick dependencies from the main repo `./package.json`. It has only the dependencies from './backend/package.json'. 

**Expected result**
Dependecies are included in the same way in both situations or appropriate note is added to readme (if not possible).

**Steps to reproduce**
1. Import any function from Lodash in index.js 
2. Try to build backend in CI.

**Comment by Sawthis** [comment]
It's not worth to do it now. We should wait for removal of service catalog and finish our refactor of modules.
