### ISSUE TITLE
Provide a graphical view of number of nodes over a period of time

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/busola#1038]
### Description

A graphical line with number of nodes

- Customers can get a clear view as and when the node usage increases and can correlate with events 
  - such as increased load
  - scaling out
  - deploying new workloads
  - among others
It also helps them keep an idea about their running costs over a period of time.
I normally use this Prometheus query `sum(kubelet_node_name)` in Grafana, perhaps it can be reused.

**Comment by valentinvieriu** [comment]
@abbi-gaurav Thank you for your request. We will try to add this to our Cluster Overview Page

**Comment by Lyczeq** [comment]
The issue has been resolved in the following PRs:
- [1#](https://github.com/kyma-project/busola/pull/1074)
- [2#](https://github.com/kyma-project/busola/pull/1079)
