### ISSUE TITLE
Visual Resources Display Statuses

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#1043]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able to differentiate easily the resources that are in a healthy or unhealthy state while looking at the visual representation of the workloads
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We will follow Fiori Guidelines when comes to the style of the resource box
- [ ] Add statuses to nodes - no need to display precise status info (that will be shown in sidebar), a colored bar will be sufficient.

<img width="269" alt="image" src="https://user-images.githubusercontent.com/10504661/156517220-6691ff1d-5062-4eb4-938e-e2cffe3227f6.png">

**Comment by wchrapka** [comment]
Delivery cost exceeds potential gains. Bars would have to be manually added to DOM, piercing through React .
