### ISSUE TITLE
Resource Graphs: Add the rest of relations

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#1046]
**Description**

0) This could be easily parallelised for different categories, clusterwide/namespaced resources etc.

1) Find out how they are connected and add them in `shared/components/ResourceGraph/relations/matchers.js` and `shared/components/ResourceGraph/relations/relations.js`.

2) Configure them on their respective details view - for some resources (e.g. Namespaces) we don't need to show the graph at all:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/10504661/156518588-03b0fc65-7df7-4ad0-9e11-1f9c1259dfd4.png">
or we could do away with shallow graph:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/10504661/156518701-59ac9334-acdf-4d85-b791-017c7fc41026.png">

- ingress
- network policy
- destination rule
- sidecar
- auth policy
- svc entry
- pvc
- volume
- subscription
- git repo
- issuer
- certifcate
- storage class
- stateful set
- deamon set
- cron job
- job

**Comment by valentinvieriu** [comment]
A task will be added for each one, on a need basis
