### ISSUE TITLE
Make sure we add hashes to files that we copy during build process

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#1050]
**Description**

We copy luigi lib and themes css files during build process. Make sure we can import them with hashes in names. Add hashes to them. Adjust cache length. 
<img width="655" alt="Screen Shot 2022-03-03 at 12 18 41" src="https://user-images.githubusercontent.com/20790348/156554891-59be9ca8-f96a-4357-996f-2c23f6b8d862.png">

Hint: Check gulpfile copy-themes and core/webpack.config.js

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by Lyczeq** [comment]
We've decided to not add hashes to the themes files because their size is not that large. It wouldn't change much.
