### ISSUE TITLE
[TESTS] Tests are randomly failing

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#1055]
**Description**
Some of the tests randomly are failing.
list of failing tests:
- protected resource
- jobs
- command pallete

**Expected result**
Tests passed.

**Comment by wchrapka** [comment]
Couldn't reproduce. A track of failed tests is essential to begin.

**Comment by mrCherry97** [comment]
Sometimes in Jobs Cypress is clicking on edit button for Selector Pod
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_busola/1069/pre-busola-integration-test-k3s/1502221649179578368

**Comment by mrCherry97** [comment]
Sometimes in Cluster Configuration Cypress doesn't see `Configuration` in leftNav
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_busola/1069/pre-busola-integration-test-k3s/1502202904734339072

**Comment by mrCherry97** [comment]
Test failed -> retest -> passed ???
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_busola/1069/pre-busola-integration-test-k3s/1502275117659459584

**Comment by mrCherry97** [comment]
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_busola/1082/pre-busola-integration-test-k3s/1503360875870818304

**Comment by mrCherry97** [comment]
@wchrapka solved problem with jobs test here: [Commit](https://github.com/kyma-project/busola/pull/1071/commits/3a384e2be7fe3564ec96399559b9f90a5b269a0e)
