### ISSUE TITLE
No tooltip for download Service Account

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1063]
**Description**

**Expected result**

Should have a tooltip

**Actual result**

**Steps to reproduce**

**Troubleshooting**

![image](https://user-images.githubusercontent.com/478866/156753273-e88cb97c-979a-410f-a2f6-73417445b728.png)

**Comment by littleamigo** [comment]
The tooltip text should describe that a kubeconfig file can be downloaded.

**Comment by littleamigo** [comment]
I can confirm the tooltip is available - thanks!
