### ISSUE TITLE
List newest custom resources first

### ISSUE THREAD

**Issue by littleamigo** [kyma-project/busola#1083]
**Description**
I have to deal with hundreds of custom resources of the same kind and would like to see the newest at the top of the list.

**Reasons**
It would save me plenty of time to find the resource of question as I have to page through the whole data set manually now and try to find the one resource with the newest timestamp-

**Comment by valentinvieriu** [comment]
We will evaluate this option, but at this moment k8s api does not support sorting
https://github.com/kubernetes/kubernetes/issues/80602

We will track this request in: https://github.com/kyma-project/busola/issues/1127
