### ISSUE TITLE
Provide a way to create a role with all api groups available in the cluster

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#1092]
**Description**
Add a way to prefill create role form with:
- all API groups 
- all resources for currently picked API groups
- all verbs

**Reasons**
Users should use the least privilege principle when assigning roles, but with many API groups and resources, the job is quite complicated and people tend to use wildcards instead of specific resources. If they are provided a simple way to populate API groups and resources they can just remove the resources or API groups that should not be accessible from the list.
Currently, Kyma provides some template roles (kyma-essentials, kyma-developer), but those roles allow too much and are not easy to adjust (you need to copy them and remove unwanted groups). Such roles also are not easy to maintain and are not modular (contain groups from all modules, even those that are not installed).

**Comment by valentinvieriu** [comment]
This has been delivered
