### ISSUE TITLE
When switching graphs, timeframe should not change

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1096]
**Description**

It would be useful, to keep the chosen timeframe when switching a graph. If I choose 6h timeframe, then switch the graph, I would expect to still see the 6h results, but I only get 1h again. 

<img width="1356" alt="Screen Shot 2022-03-17 at 10 25 10" src="https://user-images.githubusercontent.com/40663133/158778920-5388e677-75f0-46d8-84d9-d877484d8d6f.png">

**Reasons**

It's confusing that the user has to change the timeframe each time when they switch the graph. This option should be shared between all graphs.

**Attachments**

**Comment by valentinvieriu** [comment]
We will keep this behaviour for now
