### ISSUE TITLE
List View should have sorting by column

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1127]
**Description**

All the list views should have a sorting option by column. This sorting can be ascending or descending when user clicks on header 

**Reasons**

**Attachments**

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/478866/159447554-e44f877b-47ba-40d3-bc9e-a75c8bdf2b88.png">

**Comment by valentinvieriu** [comment]
It seem like the k8s api does not support sorting 
https://github.com/kubernetes/kubernetes/issues/80602

**Comment by littleamigo** [comment]
In the meantime I'm using Lens from Mirantis Inc. which supports sorting the way I need it (Age ascending) to find newest custom resource at the top.

**Comment by majakurcius** [comment]
It should be sorted by name and date (see https://github.com/kyma-project/busola/issues/1083#issue-1168494127).
(By name to be able to revert to the default sorting order).

**Comment by littleamigo** [comment]
When is this feature available in the sense of consumable? I just checked https://dashboard.kyma.cloud.sap and could not find the sorting feature yet.
