### ISSUE TITLE
Add a confirmation on Cluster disconnection / connection

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1129]
**Description**

When we delete resources, we always show `Pod/Deployment... deleted`. When we use the same button for disconnecting the Cluster from the Clusters overview list, we don't show any notification. I believe, we should be consistent, and always show success and error notifications, even if there is no call to the backend.

<img width="829" alt="Screen Shot 2022-03-22 at 10 45 31" src="https://user-images.githubusercontent.com/40663133/159452666-cd48d227-73fb-47d8-89cc-df21ec1658e6.png">

We also don't show a message that the Cluster has been successfully connected.

**Expected result**

We should be consistent when it comes to the User interactions with the lists.

**Actual result**

We don't show the message in one place only, it's inconsistent. 

**Steps to reproduce**

**Troubleshooting**

**Comment by mrCherry97** [comment]
There is a problem with confirmation info for connecting clusters, so we decide not to add it. When the cluster Is successful connected UI navigates to cluster details and when there is a problem with connecting we are displaying information about it, so notification for connecting is unnecessary. In PR we add notification for disconnecting the cluster.
