### ISSUE TITLE
Prometheus Graphs and Visual Resources are missing from the documentation

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1135]
**Description**
We have a documentation for our features, and seems the latest ones are missing from the documentation
https://github.com/kyma-project/busola/blob/main/docs/features.md

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by dariadomagala** [comment]
Added in https://github.com/kyma-project/busola/pull/1139
