### ISSUE TITLE
Choosing a preset in the edit mode, shouldn't change the non-editable field

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1166]
**Description**

If the user chooses a preset (for example in a deployment creation), Busola always overwrites all the fields in the form. It is fine for the creation but doesn't work for the edit mode. In the edit mode, it overwrites also a name of a resource, which is not editable so the edit request fails.

**Expected result**

Presets don't change the name field in the edit mode, eventually, presets are not visible in the edit mode.

**Actual result**

The name field is being changed for an already existing resource. 

**Steps to reproduce**

**Troubleshooting**

**Comment by valentinvieriu** [comment]
We should remove them in Edit Mode. Those are helping out in Create Mode only
