### ISSUE TITLE
Display Pod Template for Deployments Detail 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1206]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able see more the Pot Template section of the deployment on the deployment page
**Acceptance Criteria**

- [ ] Follow Project DOD
- [x] We will focus on key parts of the Pod Template: Containers ( Image, ENV_VARIABLES, Volumes)

Example Octant:
![image](https://user-images.githubusercontent.com/478866/161621419-bb235290-5183-4e1b-842d-284f77b91da1.png)

**Comment by mrCherry97** [comment]
View with multiple containers:
![image](https://user-images.githubusercontent.com/46759954/163188040-7bb5cdc2-e01a-4dd7-bfc3-14722f66a986.png)
