### ISSUE TITLE
VirtualService Only does not show up in Visual Resource Graph at Deployment Level 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1208]
**Description**

At Deployment Level when API Rule is provided, Virtual Service is shown, but when only Virtual Service is provided, then Virtual Service is not shown  in Visual Resource Graph at Deployment Level 

**Expected result**

Virtual Service should be shown  in Visual Resource Graph at Deployment Level 

**Actual result**

**Steps to reproduce**

**Troubleshooting**

![image](https://user-images.githubusercontent.com/478866/161684522-42915782-dba7-40c0-bc63-d9de9418a05a.png)
![image](https://user-images.githubusercontent.com/478866/161684703-f26b6481-a588-4d2a-a8ae-493d871f2ec3.png)

**Comment by Wawrzyn321** [comment]
I don't think it's a valid issue:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/10504661/161764920-f5d806a7-1a7f-4b09-9826-dc192d43a879.png">
