### ISSUE TITLE
Introduce Shortcut / to focus search

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1213]
As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer) I would like to be able use shortcuts `/` to focus on the search field
**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] We target first list views - stretch goal is to cover detail views too
- [x] typing `/` will focus on the first search field

**Comment by mrCherry97** [comment]
Add to ResourceList listener for '/' key and prop to SearchInput.
Exceptions:
- Custom Resources,
- Help Releases,
- Cluster List.

**Comment by mrCherry97** [comment]
TO DO:
- [x] disable opening search on the empty list (for now it works but not everywhere)
- [x] [WON'T FIX NOW] opening first search on details (working on HPA and API Rules, not on the rest -> need to investigate) shortcut for details has to be make in separated task
- [ ] check working flow on all resources and views
- [ ] add functionality for exceptions:
   - [ ] Custom Resources,
   - [x] Help Releases,
   - [x] Cluster List.
- [x] after opening create modal shortcut doesn't work
