### ISSUE TITLE
SPIKE: Evaluate The possibility of using Mock Backend

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1223]
**Description**

To speed up our testing would be great to use mocks instead of real k8s api server. Investigate what tools can be used to facilitate this

Minimum target is to mock first pace ( cluster overview ) so we can run Lighthouse tests on this in a predictable way.

**Possible tools to investigate**
- https://mswjs.io/

**Target timing**
2 MD

**Comment by wchrapka** [comment]
Once configured it's fairly easy to mock backend. MSWJS has the advantage of mocking the backend at the network level, so we can use same mocks in cypress, playwright AND ON DEV during development. 

Mocking means copying the API responses and including them in the code base. [This PR](https://github.com/kyma-project/busola/pull/1378/files) mocks the Cluster Overview page.  The mocks are not included in the production code built with `npm run build` if `(process.env.NODE_ENV === 'development')` is used as a wrapper.

**Comment by wchrapka** [comment]
The team decided not to proceed with the backend mock due to the need of storing the mocks or creating new mocks for each PR.
