### ISSUE TITLE
Escape special characters when navigating

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1225]
**Description**

Role Bindings might have special characters in a name (like `#`), it's not only alphanumeric. Having such a character in the URL breaks our app. We should escape such characters when we navigate to details.

**Expected result**

We should be able to display details of all resources.

**Actual result**

We cannot display details of a Role Binding that has a `#` in its name for example. 

**Steps to reproduce**

Create a Role Binding with a name for example `###`, go to it's details, 💥 app crashed.

**Troubleshooting**

**Comment by Lyczeq** [comment]
Going from a list view to the Role Binding's details works but it doesn't work after creating a resource. Deleting a resource also doesn't work as it should. When I try to delete resource named `test-###`, I encounter that problem 
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/56163767/166636474-88813602-42f8-4d88-8620-be90ff10bca6.png">
