### ISSUE TITLE
Multiple Replicasets aren't displayed on the Visual Resource Graph

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/busola#1229]
**Description**
When a resource e.g. `Deployment` has multiple `Replicasets` they aren't displayed.

**Expected result**
A group of Replicasets is displayed as one card or the most important one is displayed. This topic needs to be discussed with some k8s experts.

**Actual result**
Multiple Replicasets aren't displayed.

**Steps to reproduce**
1. Choose the `istio-system` namespace.
2. Go to the `HPA` tab and then to the `istio-ingressgateway`.
3. Scroll down to see the ResourceGraph.
4. The ResourceGraph shows only one Replicaset but it uses two - go to the `ReplicaSet` tab to check.
5. It displays the oldest `Replicaset` which has `0/0` replicas. The 'younger' one has different amount of replicas.

![image](https://user-images.githubusercontent.com/56163767/161981826-312a1ca4-0b53-442d-9814-75a4308eb53a.png)
![image](https://user-images.githubusercontent.com/56163767/161981728-6ff93b88-1e86-4d8c-9b2b-f336239f3736.png)

**Troubleshooting**

**Comment by mrCherry97** [comment]
The same is for multiple pods
![image](https://user-images.githubusercontent.com/46759954/162147963-8efed774-51a6-41e8-89e6-e6ff82dbe8a9.png)
![image](https://user-images.githubusercontent.com/46759954/162148060-efad1fde-63a3-48ff-95f8-c047594d62fd.png)
![image](https://user-images.githubusercontent.com/46759954/162148100-c6a086e5-679f-4161-a5e9-9d4bc9463c47.png)
