### ISSUE TITLE
Possibility to see a details card of the grouped resources

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/busola#1230]
**Description**
We should add a possibility to see details of grouped resources e.g. `Pods` using a `Details Card` in the `Resource Graph`.

**Reasons**
A user should have the possibility to see details of every Resource Graph component, even the grouped ones. 
Of course, we cannot display all the grouped resources at once on `Details Card` - it wouldn't be readable. My idea is to add a dropdown at the top of the `Card` where a user can choose which pod's details he wants to see.

**Attachments**

**Comment by valentinvieriu** [comment]
For now we are feature complete for this functionality
