### ISSUE TITLE
Default presets are empty

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#1263]
**Description**
As a user, when I want to choose a preset I can choose `Default` and in most of the resources `Default` Is empty.

**Expected result**
`Default` presets have default values or delete default from presets Combobox.

**Actual result**
`Default` presets are empty.
Problems in: 
- [ ] Deployments
- [ ] Gateways
- [ ] Issuers
- [ ] Secrets

**Steps to reproduce**
1. Go to deployment 
2. Click Create
3. Choose default from presets Combobox.

**Troubleshooting**

**Comment by dariadomagala** [comment]
I believe the default one is there to "clean up" what has been changed by other presets and the user's input - to roll back to what has been there by **default**. I think it makes sense to keep it, maybe just rename it, but not to remove it.

**Comment by mrCherry97** [comment]
@dariadomagala Good point, but in `Jobs` and `CronJobs` as default we set values, so it might be confusing for the user.
