### ISSUE TITLE
Move Disabled Nodes as a Feature

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1273]
**Description**

At this moment to disable nodes we have to change a special node in the config. This should be a FEATURE with a FEATURE_FLAG and configuration
**Reasons**

We need to have a unified way to control features

**Reminder**

Update the documentation :)

**Attachments**

**Comment by Wawrzyn321** [comment]
Should we address also the fact that `disabledNodes` is language-sensitive? Disabling `Configuration.Cluster Roles` won't work as expected if someone is using a different language.

**Comment by valentinvieriu** [comment]
the feature should be independent of language. When we disable a node should be disabled in all the languages
