### ISSUE TITLE
Replace @monaco-editor/react with monaco-editor

### ISSUE THREAD

**Issue by wchrapka** [kyma-project/busola#1282]
**Description**

New editor has been used already in the resource form (behind a feature flag) -src/shared/ResoureForm/fields/Editor.js . Find other usages of old editor and make them toggleable with the same feature flag. 
If needed, use the new editor but disable JSON Schema based features. For example, there is no schema for yaml upload editors at cluster/namespace level (for uploading multiple resources).

**Reasons**
- Features like tooltips should be available in read only editors
- Having one editor used throughout the app will make the user experience more coherent and will allow to remove the monaco-editor/react from the app once we feel confident about the new editor.

**Comment by mrCherry97** [comment]
@wchrapka If it's possible please remove `padding: 16px` from YAML editor in new Monaco implementation
![image](https://user-images.githubusercontent.com/46759954/167089432-44df191b-c493-411d-a108-51b6157ad604.png)
