### ISSUE TITLE
Fix create form UI

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1287]
**Description**

The current create form UI is not the best. 
* Errors hide the fields that the user is typing in
* There is a big unused space below the editor
* In deployments create view, the "create a Service" form is hidden, the user has to scroll down to see that this option even exists.

<img width="1080" alt="Screen Shot 2022-04-27 at 07 25 49" src="https://user-images.githubusercontent.com/40663133/165447275-2d6eba86-0eba-46bf-b99f-f6b7633d4865.png">
<img width="1174" alt="Screen Shot 2022-04-27 at 07 32 09" src="https://user-images.githubusercontent.com/40663133/165447645-93cde65b-fd97-46bc-aa83-7d75b9f9f879.png">
<img width="1199" alt="Screen Shot 2022-04-27 at 07 32 16" src="https://user-images.githubusercontent.com/40663133/165447650-bb29f6bf-abe8-4055-ba40-927aff28451b.png">

**Expected result**

Everything should be visible, and not scrollable if it can fit into the screen.

**Actual result**

Some things are hidden, there is a scroll because of the empty spot.

**Steps to reproduce**

**Troubleshooting**

**Comment by mrCherry97** [comment]
The new Monaco editor has the same problem.
