### ISSUE TITLE
SPIKE: evaluate if we can run kubernetes policies client side only

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1296]
We are looking into a way to be able to run a set of policies in Busola to validate if best practices are followed. 
Evaluate if we can utilize some of the shelf  solutions.

Some links to consider for evaluation:

- https://github.com/kubevious/rules-library
- https://www.jspolicy.com/
- [OPA](https://kubernetes.io/blog/2019/08/06/opa-gatekeeper-policy-and-governance-for-kubernetes/)
- https://kyverno.io/

PW: I'm assuming we'd want to not only have baked-in standard validation policies, but also support custom ones via ConfigMap-defined entries. 

| Engine    | Custom CRDs? | Rule language | Ran as an admission controller? | Language |
|-----------|--------------|---------------|---------------------------------|----------|
| kyverno   |       y      |      YAML     |                y                |    Go    |
| OPA       |       y      |    Go/Rego    |                y                |    Go    |
| jspolicy  |       y      |       JS      |                y                |    Go    |
| kubevious |       n      |  Kubik (~JS)  |                n                |    TS    |

**Comment by Wawrzyn321** [comment]
https://kyverno.io/ - I would reject it, we don't want to install custom crds on a client's cluster. How would it work anyway? It would deny the requests that violate the rules - so it's NOT running locally.

**Comment by Wawrzyn321** [comment]
OPA - just the same as kyverno, it needs to install custom CRDs.

**Comment by Wawrzyn321** [comment]
jsPolicy - it also requires a custom CRD, e.g.
```
apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "deny-default-namespace.mycompany.tld"
spec:
  operations: ["CREATE"]
  resources: ["*"]
  scope: Namespaced
  javascript: |
    if (request.namespace === "default") {
      deny("Creation of resources within the default namespace is not allowed!");
    }

```

**Comment by Wawrzyn321** [comment]
kubevious - it doesn't require any CRDs, runs via port forward. It also has a metalanguage - https://github.com/kubevious/rules-library/tree/master/library/pvc-outside-statefulset

**Comment by Wawrzyn321** [comment]
To sum up, none of those expose a clear API we could grab and use - we could just get inspired by their rulesets. I'm against importing their Go codebase and using some of their functions - we would rely on their implementation that's likely to prone.

**Comment by Wawrzyn321** [comment]
Seeing that [Datree Spike](https://github.com/kyma-project/busola/issues/1255) looks better (validation mechanism is in JS, universal schema), we won't pursue other solutions. We can grab some of their rules during [implementation task](https://github.com/kyma-project/busola/issues/1445), though.
