### ISSUE TITLE
Memory consumption graphs are always empty

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1332]
**Description**

Memory consumption graphs on a namespace details always show 0/0
<img width="671" alt="Screen Shot 2022-05-12 at 14 20 42" src="https://user-images.githubusercontent.com/40663133/168073445-fe4e7566-9fa6-4079-a420-dc2facb82de0.png">

**Expected result**

The graphs should show the actual value.

**Actual result**

The graphs are always empty.

**Steps to reproduce**

**Troubleshooting**

**Comment by valentinvieriu** [comment]
This is not really a bug, if there are no limits assigned to a namespace this shows 0/0
![Uploading image.png…]()
