### ISSUE TITLE
Editing a CRD shows an error

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1334]
**Description**

You cannot edit a CRD

**Expected result**

You should be able to edit CRD

**Actual result**

An error is shown

**Steps to reproduce**

**Troubleshooting**

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/478866/168215957-dd1cffb7-4048-4d9a-804f-6099dd6059e3.png">

**Comment by Lyczeq** [comment]
This must have been already fixed, because the bug's not present there.
