### ISSUE TITLE
Remove Service Creation when creating new Deployment

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1335]
**Description**

As we have now a separate Service Instance Creation, we should keep things separated. We will remove the Service option from the New Deployment create dialog

**Reasons**

**Attachments**

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/478866/168219508-9ec4c2b8-92e1-43c3-a2c8-707e076cd37f.png">

**Comment by majakurcius** [comment]
- [ ] Remember about updating the Get Started documentation: https://kyma-project.io/docs/kyma/latest/02-get-started/03-deploy-expose-microservice/
