### ISSUE TITLE
LogPipeline has a complete UI using the extensibility feature

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1347]
**Description**

We use the Extensibility feature to implement a complete UI for LogPipeline. This UI contains a navigation node, list, detail and edit with fields.

**Acceptance Criteria**

- [x] All the components necessary for list view, detail view and edit view are created
- [x] Navigation is Cluster level -> Kyma
- [x] We follow the DOD

**Documentation**

- https://github.com/kyma-project/kyma/pull/14063/files
- https://dashboard.dev.kyma.cloud.sap/cluster/shoot--hasselhoff--kmain/customresourcedefinitions/details/logpipelines.telemetry.kyma-project.io

![image](https://user-images.githubusercontent.com/478866/168799031-5e2f5f1f-8a3e-458a-9093-361588a72b96.png)

**Comment by majakurcius** [comment]
1. Create a ConfigMap (a small thing, creating navigation and pasting the CRD and creating empty objects for details and list) - we already have a ConfigMap so it's mostly modifying it. 
2. Insert the components into the form - Add the schema

It's not going to be baked into the cluster.

**Comment by valentinvieriu** [comment]
Here is a proposed structure for the pages
```

List 
status.condition[-a] - last condition

Detail

status:

filters
- this is a table with 1 column - multiline string - use monaco

outputs
- this is a table with 1 column - multiline string - use monaco

secretRefs
- list of secrets and deep linked

files
- this is a table with 2 column - multiline string - use monaco
- we can use name key for 1 column

parsers
- this is a table with 2 column - multiline string - use monaco
- we can use name key for 1 column



Resource Graph
- we use secretRefs


Edit/Create

- we will prefill the fields with defaults from schema


Simple 
- outputs - multiline text - monaco

Advance 
filters
- this is a  multiline string - use monaco

outputs
- this is a  multiline string - use monaco

secretRefs
- list of secrets and deep linked

files
- this is a table with 2 column - multiline string - use monaco
- we can use name key for 1 column

parsers
- this is a table with 2 column - multiline string - use monaco
- we can use name key for 1 column
```
