### ISSUE TITLE
SPIKE: Replace current implementation of Service using extensibility feature 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1348]
**Description**

We use the Extensibility feature to implement a complete UI for Service. This UI contains a navigation node, list, detail and edit with fields.

**Acceptance Criteria**

- [ ] For All the components necessary for list view, detail view and edit view issues are created
- [ ] timebox 2MD

**Comment by majakurcius** [comment]
Team decision: Prepare tests for the whole feature, not just this implementation.

**Comment by dariadomagala** [comment]
### What's missing:

1. Component for details view, to show a list of connected resources (Subscriptions and API Rules in this case)
2. Component for forms, to add an array of simple string-only arrays 

> Currently we have something like this
> <img width="1043" alt="Screen Shot 2022-06-20 at 14 26 41" src="https://user-images.githubusercontent.com/40663133/174601416-297ce44f-d08b-465a-b234-2a66a554f6a7.png">
> what is good for more complex forms, but not for the simple ones. It should be using this component (that we already have, we just need to adjust it):
> <img width="1023" alt="Screen Shot 2022-06-20 at 14 28 28" src="https://user-images.githubusercontent.com/40663133/174601698-b6557a22-c077-4140-bae1-8be5667be2f5.png">

3. Mechanism that will allow us to show more complex data. 

> For example, to show external IPs, our current code looks like this 
> ```
>   const getExternalIPs = service => {
>     if (service.status.loadBalancer?.ingress) {
>       return service.status.loadBalancer?.ingress
>         .map(endpoint => endpoint.ip || endpoint.hostname)
>         .join(', ');
>     } else if (service.spec.externalIPs?.length) {
>       return service.spec.externalIPs.join(', ');
>     } else {
>       return '-';
>     }
>   };
> ```
> What is impossible to implement using our current mechanism (without adding a very specific component). This case applies to the `external IDs` and `ports` fields.
4.  How do the translations work in forms? It ignores the values passed in the `translations` section. We either have a bug or a missing documentation.
5. Extra - we need to disable the `generate name` button on the edit view.

### Work that has been already done:
PR: https://github.com/kyma-project/busola/pull/1466
