### ISSUE TITLE
Display requests and limits in the node details

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/busola#1373]
### Description
The current node details only show usage. 
<img width="986" alt="Screenshot 2022-05-30 at 14 29 56" src="https://user-images.githubusercontent.com/4436741/170992685-72bc6252-1d75-4739-86e3-4afe50da7d7a.png">

However, from the cost perspective, it misses details such as requests and limits. 
<img width="671" alt="Screenshot 2022-05-30 at 14 22 56" src="https://user-images.githubusercontent.com/4436741/170992843-d77c1678-07df-4d01-9eaf-7294c6478a6e.png">

**Comment by lechnerc77** [comment]
+1, as also requested by customer MLP

**Comment by valentinvieriu** [comment]
This feature has been delivered. Please check
![image](https://user-images.githubusercontent.com/478866/179735810-1bcd4246-2760-4282-ab0b-e222da5d6ad7.png)
