### ISSUE TITLE
Removing a cluster from the Dashboard view looks like the User is deleting the cluster altogether

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/busola#1392]
**Description**

When I wanted to remove one of the clusters connected to my Kyma Dashboard from its view, the message that popped up asked me whether I wanted to delete the cluster and it baffled me for a second, because it looked like pressing **Delete** would delete the cluster (as in, destroy it), while the actual behaviour and intention is to just remove it from the view. 
The message and button should be changed into something clearer and unambiguous. For example, 
- `Remove {CLUSTER_NAME}` (the pop-up title), 
- `Are you sure you want to remove Cluster {CLUSTER_NAME} from the Dashboard?` (the message), and 
- `Remove` (the button). 

![image](https://user-images.githubusercontent.com/53601578/172585739-3849bb34-4d9b-40af-a8c5-1975baaa7d97.png)

**Kyma Dashboard version**: [`PR 1369`](https://github.com/kyma-project/busola/pull/1369)

**Expected result**

The message and button is clear and unambiguous. For example, 
- `Remove {CLUSTER_NAME}` (the pop-up title), 
- `Are you sure you want to remove Cluster {CLUSTER_NAME} from the Dashboard?` (the message), and 
- `Remove` (the button). 

**Actual result**

The message suggests that pressing **Delete** would delete the cluster (as in, destroy it), while the actual behaviour and intention is to just remove it from the view. 

**Steps to reproduce**

1. Open a Kyma Dashboard and navigate to **Clusters Overview**. 
2. Connect a cluster (if not already connected). 
3. Click the trash can button to remove the cluster from the Dashboard. 
4. Read the message in the pop-up window.*

*_If you previously checked the **Don't ask again** box, this box might not appear for you._

**Comment by valentinvieriu** [comment]
@grego952 feel free to pick this anytime. This is for the moment mostly a text description topic

**Comment by grego952** [comment]
@valentinvieriu that's what I thought too, but it requires some distinction in the code between `remove` and `delete` so I think one of the devs should take a look at it first.

**Comment by franpog859** [comment]
@valentinvieriu , @majakurcius , should we reopen this issue? The stalebot closed it and I don't see any results provided
