### ISSUE TITLE
EXT: Incorrect configuration displays a button that doesn't work

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/busola#1403]
**Description**
When the extension configuration is incorrect I get information and a not-working `Go back` button.

**Expected result**
Clicking on the `Go back` button should redirect me to e.g. list view of the customized resources.

**Actual result**
Clicking on the `Go back` button does nothing.
![image](https://user-images.githubusercontent.com/56163767/172799515-8fe5868c-3ed4-45ad-be9a-77a945e7bb0a.png)

**Steps to reproduce**
My configuration of the Vertical Pod Autoscaler:
The details configuration is the cause of an error.
**Resource**

```
{
  "kind": "VerticalPodAutoscalers",
  "group": "autoscaling.k8s.io",
  "version": "v1"
}
```

**Navigation**

```
{
  "path": "vertical-pod-autoscalers",
  "scope": "namespace"
}
```

**Details**
```
{
"header": [
{ "path": "spec.updatePolicy.updateMode" , "name": "Update Mode"}
],
"body":[
    {
      "name": "Container Policies",
      "path": "spec.resourcePolicy.containerPolicies",
      "widget": "Table",
      "columns": [{ "path": "containerName" }, { "path": "controlledValues" }]
    }
]
}
```

**Comment by mrCherry97** [comment]
For now, we have decided not to display a Button.
