### ISSUE TITLE
Yaml Editor is small not only in safari

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1447]
**Description**

When importing yaml in Safari, the yaml editor looks smaller than Chrome

**Expected result**

The size should be the same

**Actual result**

**Steps to reproduce**

**Troubleshooting**

![image](https://user-images.githubusercontent.com/478866/173569212-90c2da72-c95f-4a3b-a243-9be8dc5d07e5.png)

**Comment by mrCherry97** [comment]
On chrome it looks the same:
![image](https://user-images.githubusercontent.com/46759954/173570715-a2bb8e0f-93a8-45dd-b959-ac504b2f0de2.png)
height has to be calculated for the window
