### ISSUE TITLE
Metadata.namespace have strange value in create resource modal

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#1464]
**Description**

On the 'create resource' modal metadata.namespace has strange value: `namespace: !<tag:yaml.org,2002:js/undefined> ''`. This is valid for a number of resources for example: config maps, secrets. 

The same is happening for create function:
```
  deps: ''
  reference: !<tag:yaml.org,2002:js/undefined> ''
  baseDir: !<tag:yaml.org,2002:js/undefined> ''
```

**Expected result**

Should be 
```
metadata:
  namespace: ''
```
and
```
  reference: ''
  baseDir: ''
```

**Actual result**
It is like this:
```
metadata:
  namespace: !<tag:yaml.org,2002:js/undefined> ''
```
and
```
  deps: ''
  reference: !<tag:yaml.org,2002:js/undefined> ''
  baseDir: !<tag:yaml.org,2002:js/undefined> ''
```

**Steps to reproduce**
- go to config maps
- click create config map
- go to YAML
- See this`!<tag:yaml.org,2002:js/undefined>` in namespace

**Troubleshooting**

**Comment by akucharska** [comment]
<img width="1153" alt="Screen Shot 2022-06-20 at 10 10 12" src="https://user-images.githubusercontent.com/20790348/174557865-291d87ca-7f28-4f00-b987-6ed4cec46381.png">
![Uploading Screen Shot 2022-06-20 at 10.21.57.png…]()

**Comment by mrCherry97** [comment]
List of resources with this problem:
- [ ] Functions
- [ ] Config Maps
- [ ] Secrets
- [ ] Git Repositories
- [ ] Certificates
