### ISSUE TITLE
[SPIKE] Extensibility - mechanism for more complex data

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1473]
**Description**
Create a mechanism that will allow us to show more complex data. 

For example, to show external IPs, our current code looks like this 
```
  const getExternalIPs = service => {
    if (service.status.loadBalancer?.ingress) {
      return service.status.loadBalancer?.ingress
        .map(endpoint => endpoint.ip || endpoint.hostname)
        .join(', ');
    } else if (service.spec.externalIPs?.length) {
      return service.spec.externalIPs.join(', ');
    } else {
      return '-';
    }
  };
```

**Reasons**

Users might want to show something more than just one path.

**Attachments**

**Comment by valentinvieriu** [comment]
HAve a look at https://dhall-lang.org for inspiration maybe

**Comment by akucharska** [comment]
Use [Jsonata](https://github.com/jsonata-js/jsonata) to display more complex values.

Configuration in CF would look like this:
```
{ "path": "spec.toppings", formula: "$join(value.name, ', ')" }, 
{"name": "quantityIsMore", "path": "spec.toppings", formula: " $filter(value, function ($v, $i, $a) { $v.quantity > $average($a.quantity)})" }, 
```

So the only new thing is a field with a `formula`. We still can use widgets... The formula only defines how to prepare raw data for display.
The `path` is still an object. If we need to have more fields passed we should just pass the parent object for example the whole `spec`

On the code side the use of jsonata is pretty minimal:

```
export const getAdvancedValue = (resource, path, formula) => {
  const value = getValue(resource, path)
  var expression = jsonata(formula);
  var result = expression.evaluate({ value });

  return result;
};
```

**Comment by akucharska** [comment]
Will be done in https://github.com/kyma-project/busola/issues/1493
