### ISSUE TITLE
Observability view for mapping events published and subscribed

### ISSUE THREAD

**Issue by raypinto** [kyma-project/busola#1494]
**Description**

As a developer and a user of eventing in Kyma, I would like to see a mapping between events published and events already subscribed (using the Subscription CRD) in Kyma. This way I get an overview of the Subscriptions for which I have events published to and the throughput of these published events.

**Reasons**

This visualisation is important as I would like to see the current situation of the published events as well as my subscriptions. For instance:
- I would be interested to see if I've published events for which there are no subscriptions.
- I would also like to see the number of subscriptions, an event published, is sent to.
- I would like to also see if there are subscriptions for which there are multiple publishers (from various event sources).
- I might also like to see Subscriptions that do not have any publishers.

At the top of my head I would see this visualized using a [nodegraph](https://grafana.com/docs/grafana/latest/visualizations/node-graph/) where the nodes are either published events or subscriptions and the edges represents the mapping between the published events and subscriptions. An example would look like this:

![image](https://user-images.githubusercontent.com/45314732/175528401-1f6094d9-e8f7-41e0-9bf7-4c792181164f.png)

From the image, we have 4 subscriptions (in green) with their name and event-types shown on the node. We also have events published for 3 different event types (as shown in blue) with the event type and the number of events published shown on the node. We can see how one event (a.b.c) was consumed by 3 subscriptions and how one subscription (test-sub3) had two event types registered and hence received events from two different publishers. There is one subscription (test-sub4) that did not receive any event and a published event(a.b.x) did not have an associated subscription. We can assume that either the user forgot to create a subscription or there was a typo while publishing events. In addition we can further use the `event_source` data to split the blue nodes and map based on this information as well.

Looking forward to your thoughts and ideas on this. Would be a really cool feature to have and visualize for an eventing user or developer.

For implementing this feature, you could use the information from the `Subscription CR`s directly from the cluster for the 'subscriptions' nodes and for 'published events' node  you could use the metric `event_type_published` that we emit on every event that was published from the event-publisher-proxy. The metric looks like this:

![image](https://user-images.githubusercontent.com/45314732/175529986-0b832668-8318-430d-8873-21ad448052c0.png)

**Attachments**

**Comment by valentinvieriu** [comment]
We do not have the bandwidth for this feature for now. you can consider using https://github.com/kyma-project/busola/issues/2252 in the future and build this feature request as an app
