### ISSUE TITLE
Extensibilitity: Display widget: Expandable table

### ISSUE THREAD

**Issue by qbalukom** [kyma-project/busola#1500]
**Description**

Investidate a possibility of displaying data in a table with en expandable row (an expander icon that shows extra data - fully structured display - with block widgets, etc.)

**Technical notes**

- Quite possibly just extend the exisiting `Table` widget
- Possibly doable as an extra `<tr>` with `colspan=*` - but the main question how to easily integrate with with `GenericList`

**Comment by valentinvieriu** [comment]
See example from Octant:
![image](https://user-images.githubusercontent.com/478866/176174129-f9814721-a651-4257-a53e-6c8a052e1dda.png)
