### ISSUE TITLE
Busola stopped working on Safari

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1521]
**Description**

Open Busola in latest stable version of Safari ( see version ) and notice the loading spinner.

**Expected result**

Busola should work on safari 

**Actual result**

<img width="306" alt="image" src="https://user-images.githubusercontent.com/478866/176648502-370abafc-0e7b-4aa3-b176-5074306d0907.png">
<img width="802" alt="image" src="https://user-images.githubusercontent.com/478866/176648866-fb9d8270-0541-430b-960b-b91f20dcdfb9.png">

**Steps to reproduce**

**Troubleshooting**

**Comment by dariadomagala** [comment]
Fixed in https://github.com/kyma-project/busola/pull/1522
