### ISSUE TITLE
Recover language parameter in CodeViewer widget

### ISSUE THREAD

**Issue by qbalukom** [kyma-project/busola#1531]
**Description**

Re-add the feature to choose formatting language for `CodeViewer` widget.
Keep the current language detection (is it the same detection as is/was used in config maps? maybe use a single source for language detection?)
Re-add the optional `language` parameter that overrides any detection when provided.

The original parameter got removed in https://github.com/kyma-project/busola/pull/1430 (might not have been 100% implemented).

**Note**
Include information what languages are supported - potentially simply as a link to monaco.

**Comment by wchrapka** [comment]
Please add information what languages are supported (in docs)
