### ISSUE TITLE
UI for sending events

### ISSUE THREAD

**Issue by k15r** [kyma-project/busola#1537]
**Description**

As a developer using kyma to react to events I like to be able to send events directly from busola to the configured eventing backend.

**Details**

Whenever a user has to configure a subscription, or needs to invoke a workflow that is triggered using a subscription (s)he needs to send an event. Currently this involves
- either exposing the publishing proxy using an API-Rule (can be done from within busola), or portforwarding the publishing proxy (can not be done using busola)
- sending an event using curl or other tools (eg postman, cloudevents-conformance)

This might be good DX in case the developer mainly uses the console to work, but if the developer uses busola to configure and debug a workflow, this breaks the experience.

To solve this a UI that allows sending a proper cloudevent directly to EPP from busola would be useful.
Features for that UI:
- allow specifying all required cloudevents attributes. Values should be suggested by checking existing subscriptions in the cluster.
- allow specifying the event payload along with its datacontenttype
- allow specifying additional attributes ([cloudevents extensions](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/bindings/http-protocol-binding.md#2-use-of-cloudevents-attributes))
- send the configured event
- bonus: copy a working curl command that would send that exact event
- even more bonus: allow specifying an entire preconfigured event using the url, so that it can be used in documentation and tutorials
- display the resulting HTTP response code plus its error message 

**Attachments**

**Comment by valentinvieriu** [comment]
this is out of scope for now. We recommend building custom apps with custom UI for this.
We will introduce https://github.com/kyma-project/busola/issues/2252 so that you are able to link to your app in the context of Busola
