### ISSUE TITLE
Extensibility: List view: Columns with integer value 0 show as `-` instead of `0`

### ISSUE THREAD

**Issue by VaskoBozhurski** [kyma-project/busola#1538]
**Description**
I'm creating a list view for a custom resource we have and have encountered an issue with integer columns when the value of the field is `0` it actually gets displayed as `-` instead of the number.

**Expected result**

I would expect `0` values to display as `0` because that is a valid value in our case and not an issue of a field being empty.

**Actual result**
![image](https://user-images.githubusercontent.com/39486845/177177100-63c2f200-f951-4007-8565-c02570af30af.png)

**Steps to reproduce**
Below is a snippet of the list configMap entry. The fields referenced in the path are integer values in the CRD. To replicate you can use any resource field that is integer and can have a `0` value.

```
  list: |-
    [
      {
        "path": "status.summary.passed",
        "type": "integer",
        "name": "Passed"
      },
      {
        "path": "status.summary.failed",
        "type": "integer",
        "name": "Failed"
      }
    ]
```

**Troubleshooting**
This is only an issue in the list view. In the details if I reference the same fields I can have the `0`s displayed properly.

**Comment by VaskoBozhurski** [comment]
Issue also present inside details view header.
![image](https://user-images.githubusercontent.com/39486845/177315603-1e52a779-449a-4c9c-bd16-96369e1a5129.png)

**Comment by mrCherry97** [comment]
Fix in https://github.com/kyma-project/busola/pull/1524
