### ISSUE TITLE
Extensibility: Details View: Table Widget paging

### ISSUE THREAD

**Issue by VaskoBozhurski** [kyma-project/busola#1549]
**Description**
Currently the table widget shows all items and there is no paging. This means that if we have too many results it makes the details page very long. Perhaps introduce a way to limit the number of results and create paging so that users would not need to scroll in case of many entries.

**Reasons**
Our custom resources can have very long lists with double to triple digit entries and displaying them all at once would make a very non-UX friendly experience.

**Comment by valentinvieriu** [comment]
We don't have the bandwidth for this feature for now.
We will close it
