### ISSUE TITLE
Extensibility: Form View: Able to enhance/patch the CRD schema

### ISSUE THREAD

**Issue by VaskoBozhurski** [kyma-project/busola#1551]
**Description**
Be able to further enhance the existing CRD schema that is used inside the Form View so that fields can be further adjusted with enum values and perhaps toggleable visibility so that the Create/Update UI is more precise and easy to use by users of the CRD.

**Reasons**
For our resource we actually use the `metadata.name` to describe which entity we want installed (we do this because we want to ensure each resource references a unique entity and you can not have 2 resources for the same entity.)

Another use case we would have is in the KamarotosPolicy's `spec.config.<...>` fields which are only applicable depending on the `spec.type` field. In our case we would like to hide the configuration of certain fields when they are not applicable for the type in question.

Currently our CRD generation is done using [Kubebuilder](https://book.kubebuilder.io/) and by annotating our golang code with the specific comments that kubebuilder's controller-runtime executable processes. This means that ever time we build our operator, the CRD yamls are rebuild from the comments and we are limited by this in writing some more advanced schemas. If we are able to further enhance the schema we have with a patch or otherwise from the configMap, we would be able to code the extra functionality we want.

**Comment by Wawrzyn321** [comment]
Most of the requested features are already implemented. We decided not to allow for changes in `metadata.name`.
