### ISSUE TITLE
Extensibility: List View: Specify that the create button should be disabled

### ISSUE THREAD

**Issue by VaskoBozhurski** [kyma-project/busola#1554]
**Description**
Allow the possibility to disable the Create button for certain custom resources.

**Reasons**
We have a resource that serves as a report from the work that our operator has done. As such the user has no business creating an instance of that resource. This is very similar to how you can not create Events from the Kyma Dashboard either.

**Comment by valentinvieriu** [comment]
closed by https://github.com/kyma-project/busola/issues/1557
