### ISSUE TITLE
Extensibility: Form View: Define form field names

### ISSUE THREAD

**Issue by VaskoBozhurski** [kyma-project/busola#1555]
**Description**
I want to be able to define a pretty text name for different fields the user should supply. For instance I want it to be `Type` instead of `spec.type` on the left side of the form field.

**Reasons**
In the details view the fields are already having the pretty name so I believe it would be more user friendly if when creating or editing a resource they see the same pretty names instead of the json path.

**Attachments**
![image](https://user-images.githubusercontent.com/39486845/177321787-fa35170e-74e1-4846-a72b-ad92f69c3d20.png)

**Comment by valentinvieriu** [comment]
Check if this is duplicate for https://github.com/kyma-project/busola/issues/1569

**Comment by dariadomagala** [comment]
> Found a workaround by using the `translations` to specify custom names for most form widgets, but it does not work with `"widget": "SimpleList"` as that one overrides the name. :(

Hi! Translations are not a workaround, it's the desired approach. Busola can potentially be translated to many languages - it's not translated yet, but we have the mechanism for that already and we want to be consistent also in the extensibility views.

It's true that it doesn't work properly for the SimpleList widget now, good catch! We have a [PR](https://github.com/kyma-project/busola/pull/1644/) with a fix ready.
