### ISSUE TITLE
Add extensibility tests

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1556]
**Description**

Add tests for the extensibility views (e2e and unit tests). 
Thought: maybe we could reuse the examples folder for the tests, to also test if examples are up-to-date?

- [x] adjust the CI pipeline
- [x] create a test for the Pizza examples
- [x] update examples/resources
- [x] ~create a test for the Certificates examples (see Pizzas)~ example has been removed
- [x] ~create a test for the Git Repos examples (see Pizzas)~ example has been removed
- [x] create a test for the Services examples (see Pizzas)

**Reasons**

Extensibility is a big feature, we should make sure it is stable.

**Attachments**

**Comment by dariadomagala** [comment]
It has been resolved only partially, we should proceed with the tests

**Comment by valentinvieriu** [comment]
Consider id this is faster to run this in Docker for the Cypress tests
