### ISSUE TITLE
Extensibility: Form View: KeyValuePair not working?

### ISSUE THREAD

**Issue by VaskoBozhurski** [kyma-project/busola#1558]
**Description**
I am trying to create a KeyValuePair widget for users to add labels inside my `spec.selector.labels` field.

**Expected result**
![image](https://user-images.githubusercontent.com/39486845/177336526-45ff2da3-5e57-4766-8ddd-c840bbf05006.png)

**Actual result**
There is nothing.

**Steps to reproduce**
```
      {
        "simple": "true",
        "path": "spec.selector.labels[]",
        "widget": "KeyValuePair"
      },
```

**Comment by mrCherry97** [comment]
Hi @VaskoBozhurski 
We repaired the problem with `KeyValuePair` and we had an issue with documentation. When you are making a form for `KeyValuePair` you don't need `[]`. So in your case, it should be like this:
```
      {
        "simple": "true",
        "path": "spec.selector.labels",
        "widget": "KeyValuePair"
      },
```

**Comment by VaskoBozhurski** [comment]
Just tested and it works as intended. Thanks!
