### ISSUE TITLE
Extensibility: Details View: Simpler ResourceRef-like widget

### ISSUE THREAD

**Issue by VaskoBozhurski** [kyma-project/busola#1561]
**Description**
New ResourceRef-like widget that only creates a hyperlinked text with the name of the resource and not a whole panel with columns and everything.

**Reasons**
We would like to have a much simpler ResourceRef-like widget which does not create a new panel with columns and links so that we can more compactly create resource links between our resource and other related resources. These links would then be embeded into other panels on a single line so that it takes less space and is more readable.

**Attachments**

Current ResourceRef:
![image](https://user-images.githubusercontent.com/39486845/177565630-a26222fb-d641-408b-9eb8-c3a03a4096ec.png)

Requested ResourceRef-like widget:
![image](https://user-images.githubusercontent.com/39486845/177566058-3739ce7a-d01a-44ed-91ca-d2ab2f199adb.png)

**Comment by valentinvieriu** [comment]
Suggested name ResourceLink ?
