### ISSUE TITLE
Handle HPAs in preferred version (v2beta2 -> v2)

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#1566]
**Description**

We should use preferred version of the resources all the time. In case of HPAs, that would be `v2`, while we are using `v2beta2`. Smooth upgrade is impossible, since in `v2` the new one a field (`metrics`) was removed / made optional. Let's research if an upgrade is viable.

**Comment by Wawrzyn321** [comment]
Bonus task - if upgrade is successful, remove HPAs `if` statement in `core-ui/src/hooks/useVersionWarning.js`, if upgrade is impossible remove the link to this issue from the codebase.

**Comment by Lyczeq** [comment]
HPA v2 version was introduced in Kubernetes 1.23, so we should wait for this task until that version is the default one for Kyma.
