### ISSUE TITLE
The description is missing from some of our views

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1600]
**Description**

The description is missing for API Rules and Git Repositories ( possible other sections ). This situation occurs when an extensibility is created for the same component
**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

![image](https://user-images.githubusercontent.com/478866/178981199-3efa9868-7de6-4890-ac86-2527c535b417.png)

**Comment by dariadomagala** [comment]
The issue is not about missing descriptions. When the user creates an extensibility configuration with the same path as the built-in busola view, it overwrites the busola view.

This is a desired approach
