### ISSUE TITLE
Environment Variables in Functions CSS

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#1603]
**Description**
Create is under Search icon

**Expected result**
Search icon is in the same line as create

**Actual result**
![image](https://user-images.githubusercontent.com/46759954/178991344-536b39fb-eb46-45b2-9eec-630252998945.png)

**Steps to reproduce**
1. Create a function
2. Go to details
3. Check UI

**Troubleshooting**

**Comment by Lyczeq** [comment]
This must have been already fixed, because the bug's not present there. 
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/56163767/184841529-04bc198e-f4ee-4910-b1b7-2406920d5975.png">
