### ISSUE TITLE
Unexpected version of CronJobs: expected v1, got v1beta1

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1609]
**Description**

It seems there is a new version of CronJobs 

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by dariadomagala** [comment]
Also, there was a similar issue for 
```Unexpected version of AlertmanagerConfig: expected v1, got v1alpha1.```
happening on the `customresourcedefinitions` view.
