### ISSUE TITLE
Extensibility creator UI leaves a lot of spam in resultant config map

### ISSUE THREAD

**Issue by qbalukom** [kyma-project/busola#1611]
**Description**
When creating a new extensibility plugin via UI it puts unncessary items into the resultant code that are not actually used or are unnecessary. Most importantly the "type" value - both in details and form view.

**Expected result**

The resulting JSONs should be clean and without any additional variables.

**Actual result**

The resulting JSONs should be clean and without any additional variables.
- type in both `details` and `form`
- name in `details`
- path in `resource`

**Steps to reproduce**

Create any resource plugin via the UI.

**Troubleshooting**

**Comment by valentinvieriu** [comment]
fixed by https://github.com/kyma-project/busola/issues/1655
