### ISSUE TITLE
Adjust Busola pipelines to work with the newer k8s 

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#1620]
**Description**

The current implementation of our pipelines doesn't allow us to use the newest k8s version. Rewrite it to not use kyma-local, we can use kyma cli or our own approach.

**Expected result**

Busola runs on the newest k3d clusters

**Actual result**

Busola runs on an old k3d

**Steps to reproduce**

**Troubleshooting**

Quick draft, that didn't work but might help with searching where to look for it :) https://github.com/kyma-project/test-infra/pull/5711/files

**Comment by Wawrzyn321** [comment]
Done in https://github.com/kyma-project/test-infra/pull/5830
