### ISSUE TITLE
EXTENSIBILITY: SPIKE Simplify the json schema / Open API to forms mapping

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1626]
**Description**

It seems we have a complex implementation that has a high probability to slow our future development. Evaluate and implement the changes that are needed to reduce the complexity of the json schema to forms mappings that

**Reasons**

**Possible Steps**

1. Create a function mapping entries from the config map to EXT details and adjust StringRenderer component, convert the form state from schema-ui to our regular form state.
- At the moment widgets receive a state adjusted to ui-schema in an immutable variable, get back to our regular state
- Adjust the app to accept the structure as in the detail and list views (with children)
      ```{
        "path": "spec.files",
        "children": [{"path": "name"}, {"path": "content"}]
      }```
- Adjust translations (tested in the spike)
2. Adjust the remaining base components
- SwitchRenderer (tested in the spike)
- NumberRenderer
- GenericList (tested in the spike)
3. Adjust the custom components (if some are more complex, let's separate the tasks)
- NameRenderer
- KeyValuePairRenderer
- MonacoRenderer
- CollapsibleRenderer
- ResourceRefRender
- ResourceRenderer
4. Add validation on the form level (and pass to fields via props). Or at the field level and inform parent when value updated?

**Comment by wchrapka** [comment]
After a discussion, the code owners decided to keep the current, already implemented solution as long it doesn't require a change. The alternatives would introduce a similar level of complexity.
