### ISSUE TITLE
Finalize Busola Extensibility API

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1655]
**Description**

It's time to finalise the Busola Extensibility by configuration api. 

**Acceptance criteraia**

- [ ] All Fields in the configmap are revisited and evaluated if they are needed or not or need to be rename or modifiy
- [x] Not needed fields in the configmap are removed ( eg schema )
- [ ] Example folder and documentation is adjusted
- [x] a first version is established with beta tag
- [x] the Create View is adjusted so it creates a valid configmap
- [x] Components in docs are sorted
- [x] Remove unnecessary components (e.g. `ControlledByKind` is a dupe of `ControlledBy`)
- [x] Align usage of resource references - relations don't need to specify `group` for `core` resources (just like `Resource` widget does).

**Attachments**

**Comment by majakurcius** [comment]
Note: If there are fields that are similar, they should have the same format.

**Comment by Wawrzyn321** [comment]
To discuss - should we use yaml by default instead of json in configmap sections?

**Comment by Wawrzyn321** [comment]
Another idea - I don't particularly like keeping the version as a standalone field in configmap `data`. Maybe put the version into the labels or add a `data` field named `metadata` (an object), where `version` would be just one of many fields? That would be easier to change, if we are to add more metadata.

**Comment by Wawrzyn321** [comment]
From Vasko: it's a little bit inconsistent how we use the `children` property in details and list, but we cannot use them on the form.

```json
 { "path": "spec.toppings", "widget": "GenericList", "simple": true},
 { "path": "spec.toppings[].name", "simple": true},
 { "path": "spec.toppings[].price", "simple": true},
 { "path": "spec.toppings[].quantity", "simple": true},
```

Would be nicer to have it like: 
```json
 { "path": "spec.toppings", "widget": "GenericList", "simple": true,
	"children": [
		{"path": "name"}
		...
	]

 },
```

**Comment by Wawrzyn321** [comment]
relations -> dataSources

**Comment by Wawrzyn321** [comment]
Closed since all the subtasks are already created. More info on Mural - https://app.mural.co/t/sappm1454/m/sappm1454/1659423961015/4ef68d23fc46b1e3a4597db6136a7272860fdee2?wid=0-1659426885250&sender=piotrwawrzynczyk1858
