### ISSUE TITLE
Ext: Inline array widget

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#1664]
**Description**

New widget that would render its items inline, each as a separate Widget.

**Reasons**

JoinedArray does something similar, but it displays the items as a strings. We would like to render a collection of links, badges, etc.

**Attachments**

This works only because the keys ("passed", "skipped", "failed") are known and iterated manually. We need a solution for a collection with any number of items.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/10504661/181451393-e9cc9f1d-b16c-4903-9650-d298c8ffccff.png">

**Comment by VaskoBozhurski** [comment]
I didn't see that this exists so I created a duplicate at #1667 . Feel free to copy it or close it as you choose.

**Comment by Wawrzyn321** [comment]
Closing as duplicate of #1667
