### ISSUE TITLE
Extensibility: Details/List View: Disable delete/edit buttons.

### ISSUE THREAD

**Issue by VaskoBozhurski** [kyma-project/busola#1670]
**Description**
Provide a way to dissable the delete and/or the edit button in the extensibility views for certain resources.

**Reasons**
Our report resources are generated by the operator and should not be edited by the user, because they are intended to be a read only (by the user) resource, much the like the status field of many k8s resources. 

**Attachments**
#1554 is a similar item about the create button.

**Comment by valentinvieriu** [comment]
We have disableCreate flag now for some widgets. Please add the same pattern for disableEdit and disableDelete
