### ISSUE TITLE
Deployment runtime dropdowns are not in the same line as inputs

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#1678]
**Description**
Dropdowns for runtimes should be in the same line as input.

**Expected result**
Dropdowns aren't in the same line as inputs.

**Actual result**
![image](https://user-images.githubusercontent.com/46759954/181727015-9d7d3bc2-0d4b-4437-a2f2-ee707d7129a5.png)

**Steps to reproduce**
1. Go to Create Deployment
2. Go to Advance 
3. Check UI

**Troubleshooting**

**Comment by Lyczeq** [comment]
The issue will be fixed in the following [PR](https://github.com/kyma-project/busola/pull/1661).
