### ISSUE TITLE
Backend: Limitation on Throughput

### ISSUE THREAD

**Issue by PoojaGidaveer** [kyma-project/busola#1693]
**Performance Tests triggered on backend application on Initial HomePage -**
API - /events, /nodes

**Inferences-**
1. Started with 1 and scaled till 4 instances of the backend and max Throughput that we could achieve was 600req/s.
2. Comparison Tests on Apiserver gave the throughput more than 3k req/s
3. Apiserver can process requests upto 4kreq/s where as same 4 instances of backend can process max of 600req/s
4. More details can be found here- https://github.tools.sap/engsrvperformance/Kyma-Performance/tree/main/docs/Initial_HomePage_Tests

**Limitation**
Backend is limited to 600req/s

**Expected Behaviour**
Backend should give throughput similar to apiserver requests

**Comment by valentinvieriu** [comment]
Thank you for the issue we will investigate this issue but at this moment the volume we are seeing it's not a concern yet.
We will schedule a backend optimisation in the future

**Comment by valentinvieriu** [comment]
We have countermeasures to scale horizontally using Google Cloud Run to contra measures
