### ISSUE TITLE
Web: CSS file blocked for 2s

### ISSUE THREAD

**Issue by PoojaGidaveer** [kyma-project/busola#1694]
**Performance Tests triggered on Kyma Dashboard** 

Test Setup: 1user, 10iteration

Higher response time upto 4s is observed on overview page when hosted the kyma dashboard repeatedly.

Waterfall analysis for loading of page /cluster/shoot--perftests--ngrinder/overview shows that all the resource Requests like css are taking more than 2s of Response Time. 2s of Response Time is mainly because of blocking-

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/33653955/182528458-de9f069c-39f6-4df9-af68-fa2df444f3cf.png">

**Comment by valentinvieriu** [comment]
We cannot reproduce this in our environment. we will have a deeper look at our performance, but at this moment this seems to be related to the setup you have there
