### ISSUE TITLE
Feature Request: Versioning

### ISSUE THREAD

**Issue by KaiReichart** [kyma-project/busola#1708]
**Description**
We are working on integrating the busola dashboard into an offering, and as such rely on stable and reliable software.  
Currently, it is not really clear which commits are considered stable and what the changes are between X commits.

Therefore, versioning with changelogs and stable releases would be very beneficial for us.

It would probably be sufficient to have tags in Github, and have the changelogs as a file in the repo.  
Semantic versioning would be a plus, but not strictly necessary.

**Comment by valentinvieriu** [comment]
Still valid request. We had no time to work on it.
