### ISSUE TITLE
Feature Request: Always show `Upload YAML` button

### ISSUE THREAD

**Issue by KaiReichart** [kyma-project/busola#1713]
**Description**

The `Upload YAML` button currently is only shown in the Cluster and Namespace Overview page.  
It would be beneficial from a users standpoint to have the button always accessible, maybe in the nav bar like so:
![Screenshot 2022-08-04 at 10 24 27](https://user-images.githubusercontent.com/29383712/182800411-e2f83322-afd0-467e-8002-a17f3b7293f8.png)

If no namespace is provided in the yaml, the current namespace should be used (NOT the default namespace)

**Reasons**

This would reduce friction, and speed up quick deployments and debugging.  
For example: I am debugging why a pod is not getting ready. I need to deploy a new role and rolebinding. 
Currently, I need to 
- Find the Roles page in busola and upload the role there
- Find the Rolebindings page, and upload the RB
- Go back to the pods page and restart the pod

If the `Upload YAML` button was accessible from there, I would not need to do any of this and could do everything directly from the pods page.

**Comment by valentinvieriu** [comment]
We plan on inttroducing a ctr+k shortcut for this feature so you can pop up the upload yaml view from any part of the app
