### ISSUE TITLE
EXT: Deleting a resource displays incorrect name

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/busola#1715]
**Description**
When I try to delete a resource in the view created by the Extensibility feature the notification displays incorrect name.

**Expected result**

Notification popup displays correct kind of the resource I've deleted e.g. `Git Repository deleted` instead of `Example deleted`.

**Actual result**

Deleting Git Repository resource from our examples directory displays `Example deleted` instead of  `Git Repository deleted` because it is based on the url.

![image](https://user-images.githubusercontent.com/56163767/182818573-09402a99-d1d9-491d-a986-a36a11bd8c3f.png)
---
![image](https://user-images.githubusercontent.com/56163767/182818621-9cab3a35-4398-4cee-b484-989c5d6faf63.png)

There is similar situation but a bit better for PizzaOrder:
The name is `Pizzaorder` instead of `Pizza Order`

![image](https://user-images.githubusercontent.com/56163767/182819233-0c87325c-5219-48af-bdd2-b42b0ebfb1b3.png)
---
![image](https://user-images.githubusercontent.com/56163767/182819329-8dbe6b18-0ba1-4e3d-a3be-1e1fc0763ea9.png)

**Steps to reproduce**
1. Create a ext. view using examples folder
2. Create the resource
3. Delete it, you should see incorrect notification.

**Troubleshooting**

**Comment by dariadomagala** [comment]
After the latest changes, it also doesn't work with titles and breadcrumbs. It is also handled in the linked pull request.
