### ISSUE TITLE
Failing `run-after` test for namespaces

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#1741]
**Description**
There are more and more situations where this test is failing. Cypress is clicking on the `Delete` tooltip or button in the backdrop and the namespace can't be deleted.

**Expected result**
Tests are passing without `/retest`

**Actual result**
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_busola/1740/pre-busola-integration-test-k3s-namespace/1557620794555633664

**Steps to reproduce**
1. Open PR
2. Run tests

**Troubleshooting**

**Comment by wchrapka** [comment]
The detached element is re-rendered by React. We could either check why it happens and fix the rerendering or use cypress `click({force: true})`
