### ISSUE TITLE
The extensibility feature does not work for namespace only access

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1753]
**Description**

At this moment the extensibility feature does not work for namespace only users as we are getting all the configmaps at the cluster level and filter them by label

**Expected result**

Extensibility should work for namespace only users.

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by Wawrzyn321** [comment]
It does work - if the `namespace` is set in their kubeconfig or set in this view
<img width="661" alt="image" src="https://user-images.githubusercontent.com/10504661/186908699-899caf3d-23b2-4078-b92e-69b2cde77665.png">
it will be used during the call for configmaps (defaulting to `kube-public`).

Should we close this?
