### ISSUE TITLE
Unable to open cluster from Clusters Overview

### ISSUE THREAD

**Issue by ramosmike** [kyma-project/busola#1784]
When trying to login into the Kyma Dashboard (BTP Kyma), I'm getting redirected to the "Clusters Overview" page where I can see my cluster listed.

After clicking in the cluster name, same thing happens and I get redirected to the same "Clusters Overview" page. During the redirection I can see the OpenID flow taking place correctly.

On the next sequence of requests, the only abnormal thing I see is a 404 from `https://dashboard.stage.kyma.cloud.sap/backend/api/v1/namespaces/kube-public/configmaps/busola-config`:
```
{kind: "Status", apiVersion: "v1", metadata: {}, status: "Failure",…}
apiVersion: "v1"
code: 404
details: {name: "busola-config", kind: "configmaps"}
kind: "configmaps"
name: "busola-config"
kind: "Status"
message: "configmaps \"busola-config\" not found"
metadata: {}
reason: "NotFound"
status: "Failure"
```

After cleaning up all cookies the issue is gone and behavior is back to normal.

**Comment by valentinvieriu** [comment]
@ramosmike getting a 404 on that file is normal. We are trying to discover what is running in your cluster.
Unfortunately the steps provided will not help us to reproduce the bug
