### ISSUE TITLE
EXT: some widgets has missing docs

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#1785]
**Description**
For example widget `number` is not described in docs.
We have to check whole docs and fix missing information (widget-specific parameters etc.)

**Area**

**Reasons**

**Attachments**

**Comment by Lyczeq** [comment]
Table widget documentation misses the the important information on how to define children. Current docs doesn't include of using an $item variable in the children section. The current example looks as follows:
```json
{
  "source": "spec.item-list",
  "widget": "Table",
  "children": [{ "source": "name" }, { "source": "status" }],
  "collapsible": [{ "source": "description" }]
}
```

Unfortunately it doesn't work and the proper should be:
```json
{
  "source": "spec.item-list",
  "widget": "Table",
  "children": [{ "source": "$item.name" }, { "source": "$item.status" }],
  "collapsible": [{ "source": "$item.description" }]
}
```

**Comment by Lyczeq** [comment]
The documentation of the Table and ResourceList was fixed in the following [PR](https://github.com/kyma-project/busola/pull/1791).
