### ISSUE TITLE
Search slash shortcut is bugged when using Yaml Editor on a List view

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/busola#1797]
**Description**

**Expected result**
I would like to use a `/` char without any problems when editing a resource on a list view. 

**Actual result**
Typing a `/` char while editing a resource in the Yaml on the list view triggers the slash shortcut to search in the list. It shoudn't work like that. I should be able to use that character without any problems in the Yaml editor that slides from the right.

**Steps to reproduce**

1. Go to any resource list e.g. Deployments.
2. Click on the Edit button on one of the items and wait until Yaml editor slides from the right.
3. Type `/` inside of that Editor - after that, you no longer edit the resource, you are searching the list view.

**Troubleshooting**

**Comment by barchw** [comment]
Hi @kyma-project/hasselhoff, I can reproduce that issue again:
1. Open resource
2. Open edit
3. Type `/`
4. `/` is not typed, but opens search
