### ISSUE TITLE
Can't create API Rule without ClusterRole to read Gateways

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#1832]
**Description**

User with namespace permissions can't create API Rule. 

**Expected result**

If Gateway exists in the namespace user should be able to create an API Rule referencing that gateway. List gateways from the current namespace first and then optionally all other gateways (the second operation can fail with 403 what should be ignored by UI). 

**Actual result**

403 error for getting cluster-wide resource:
`https://dashboard.kyma.cloud.sap/backend/apis/networking.istio.io/v1beta1/gateways` is propagated to the UI.

**Steps to reproduce**

Create a namespace and service account with cluster-admin role in that namespace. Create Istio gateway and then try to create API Rule. You can't use the Gateway in the UI (with kubectl it is possible to create such API Rule).

**Troubleshooting**

**Comment by akucharska** [comment]
Fixed in #1865. In case the user doesn't have rights to get gateways we display input pre-filled with `kyma-gateway`

**Comment by valentinvieriu** [comment]
We need to make sure that users with namespace access only can see the gateways too. I think our implementation does not cover this usecase yet

**Comment by mrCherry97** [comment]
Hi @pbochynski,
everything should works fine now, user with namespace access only can see gateways and as Agata mention, we are displaying pre-filled input for Gateway in ApiRule Create modal. Please double-check and if problem appears please reopen the issue.
