### ISSUE TITLE
Role Selection from RoleBinding does not allow free text

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1849]
**Description**

The Form Validation fails if free text is typed in

**Expected result**

User should be able to add free text and the form should be valid

**Actual result**

**Steps to reproduce**

**Troubleshooting**

<img width="774" alt="image" src="https://user-images.githubusercontent.com/478866/190362681-8b8ee9a2-e215-46b4-8327-a5f31f629cc2.png">

**Comment by jalibu** [comment]
Free text entries are most likely of kind ClusterRole that the respective user is not allowed to list due to lack of cluster scoped authorizations.
