### ISSUE TITLE
EXTENSIBILITY: Migrate API Rule to extensibility

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1865]
Description

Move API Rule functionality to an extension.

**Acceptance Criteria**

- [x] The application behaves and looks as similar as possible - changes are accepted
- [x] Test are adjusted
- [x] We try to reuse the existing widgets. If new widgets are needed, they need to be created and documented
- [x] https://github.com/kyma-project/busola/issues/1832
- [x] https://github.com/kyma-project/busola/issues/1767

**Comment by akucharska** [comment]
Overwrite flag moved to: https://github.com/kyma-project/busola/pull/1998
