### ISSUE TITLE
UX: convert all the buttons to have an icon before text

### ISSUE THREAD

**Issue by qbalukom** [kyma-project/busola#1878]
All buttons that have an icon should have the icon before text instead of after.

**hint**:
Use the `iconBeforeText` flag.

**Comment by valentinvieriu** [comment]
Can we choose to have Tooltips to both Add and Remove.
And also add ( or remove ) the labels to both buttons
![image](https://user-images.githubusercontent.com/478866/193054437-43c07d77-95ee-42dc-863a-5e00c1786da6.png)

**Comment by mrCherry97** [comment]
With team we decide to not add labels `Remove` to the trash icon and stay with labels `Add` next to plus, also we agreed that Tooltips here aren't necessary. We can discuss it later and make a follow-up if it will be necessary.
