### ISSUE TITLE
When RuntimeInfo and ShootInfo are not available, Busola Breaks

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#1885]
**Description**

When RuntimeInfo and ShootInfo are not available, Busola Breaks and no navigation is posible.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by Wawrzyn321** [comment]
How to reproduce that? I've checked it on `k3d` cluster where this info is not available, it works just fine.

**Comment by dariadomagala** [comment]
I also wasn't able to reproduce it by breaking the urls and getting 404s

**Comment by Wawrzyn321** [comment]
It can be reproduced with a cluster from GCP (https://console.cloud.google.com/kubernetes/list/overview?project=sap-ti-dx-kyma-mps-dev). The nodes call waits for calls for prometheus services:
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/10504661/195070352-00785a42-5087-42d4-af3d-0ac540d8eefb.png">

Hovever, other calls (events) seem to be fine.
