### ISSUE TITLE
Introduce extension schema validation

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#1890]
**Description**

Make it possible to validate the current extension configuration against the schema, which would need to be updated by us on code-change basis. We should use this validation to guide the user while editing an extension on our ConfigMap edit view.

As a base we could use "schema-*.json" files in `/core/src/assets/customResources`.

**Snipped from our code (removed)**

```js
  const ajv = new Ajv();
  if (!ajv.validate(extensibilitySchemas?.details, resMetaData?.details)) {
    throwConfigError(t('extensibility.configuration-error'), { error: ajv.errors });
  }
```

**Comment by valentinvieriu** [comment]
Is it possible to introduce the schema validation to the editor? Before saving the extension
