### ISSUE TITLE
Rewrite Luigi side menu

### ISSUE THREAD

**Issue by wchrapka** [kyma-project/busola#1939]
**Description**

- [x] create onClick fn for links in the navigation https://github.com/kyma-project/busola/pull/1981
- [x] map static navigation nodes to resources/***/index.js  https://github.com/kyma-project/busola/pull/1937
- [x] move footer https://github.com/kyma-project/busola/pull/1969
- [x] create fn to assemble the navigation structure based on re-maped nodes 
- [x] write unit test for the logic
- [x] style and html the navigation JS object with fundamental
- [x] handle the unusual nodes (CR, Extensibility, Halm, External) https://github.com/kyma-project/busola/pull/1978
- [x] create a config map toggle
- [x] handle the external nodes https://github.com/kyma-project/busola/pull/1993

Uncovered issues:

- [x] selectors reload too often as a config feature `prometheus` loads few times https://github.com/kyma-project/busola/pull/1987

**Comment by dariadomagala** [comment]
Things still to do as a follow-up:

- [ ] External nodes - add an icon next to the node name showing that it's external. (it's implemented in fundamental, but the types don't match)
- [ ] Hide all popovers after clicking on them (for example namespaces dropdown stays open after changing the namespace)
- [ ] If changing a cluster fails, the navigation doesn't happen, but the name in the header shows the new cluster name (maybe it will be fixed after the removal of Luigi?)
- [ ] Make the left side nav smaller on mobile/small screens
- [ ] Write tests
