### ISSUE TITLE
Document keyboard shortcuts ect

### ISSUE THREAD

**Issue by dariadomagala-sap** [kyma-project/busola#1975]
**Description**

In Busola we have some keyboard shortcuts like `cmd+k` or `/` yet not everyone knows about it because it wasn't documented. Document all keyboard shortcuts or possibly other features if are not yet documented.

**Reasons**

Everyone should know about such features and how to use them.

**Assignees**

@kyma-project/hasselhoff 
@kyma-project/technical-writers

**Attachments**

**Comment by mrCherry97** [comment]
Maybe we can add an icon like GitHub to the Search input
<img width="289" alt="image" src="https://user-images.githubusercontent.com/46759954/197189695-27d4bd08-6fd1-4ed6-bed0-b1e33272016c.png">

**Comment by VishnAndr** [comment]
Hi, just found this issue. Even though shortcuts exist and great, they definetely should be documented.

However, there is an issue with `/` shortcut. When I'm maintaining function code in inline editor and trying to comment something in Nodejs type function basically putting `/` in the inline editor, the cursor jumps to the search field of environment variables. Not very convinient. Should the `/` be excluded in the inline editor? Should I open a separate issue for this?

**Comment by ptesny** [comment]
Hello, @VishnAndr , I have already raised a [bug](https://github.tools.sap/kyma/backlog/issues/3045) with regard to the following issue.

> When I'm maintaining function code in inline editor and trying to comment something in Nodejs type function basically putting `/` in the inline editor, the cursor jumps to the search field of environment variables. Not very convinient.

On a side note it seems that if you select nodejs16 as a function runtime the above does not happen....

**Comment by VishnAndr** [comment]
Hi @ptesny , thanks! Looks like the one you mentioned is an internal bug report, no?
I'm having the issue with Nodejs16 actually. Kyma Dashboard version: [93a6b822](https://github.com/kyma-project/busola/commit/93a6b822) if it makes any difference.

**Comment by VishnAndr** [comment]
Actually as I can see the type of the function doesn't matter. Nodejs14, Nodejs16, Python etc. - all have the same issue in inline editor. The prerequisite to reproduce is to have at least one env variable. This enables the search button in the env variables section and here the issue starts to appear. If you don't have env vars, all good, it won't open the search because it is disabled.
