### ISSUE TITLE
Provide a capability to launch a shell with preconfigured tooling from the console UI

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/busola#198]
### Description

Similar to google cloud shell, we can provide a shell that the user can launch and run various commands to try out samples.

![image](https://user-images.githubusercontent.com/4436741/121211290-a8e4d100-c87c-11eb-8888-3e2f9dc31514.png)

### Motivation

Often, developers have challenges installing required tooling such as docker, kubectl, helm, others...
There could be constraints from their IT department, company policies.

Another set of users exploring cloud-native technologies such as Kyma is middle to upper management, such as Product Managers, CTOs. They would not bother spending time to set up the prerequisite tooling.

For both such cases, having an option to activate a shell and just use it would be a huge benefit.

Reference to gardener ops-toolbelt image: <https://github.com/gardener/ops-toolbelt/tree/master>

**Comment by valentinvieriu** [comment]
We decided not to have this feature in the near future. It is added in our backlog of nice to haves for now.
Thank you @abbi-gaurav
