### ISSUE TITLE
Separate kyma-dashboard from Busola

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#1989]
We need to move all kyma-specific stuff from Busola, according to a diagram:
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/10504661/198225000-7ab72015-78f8-448d-9e03-b69e39dd6f09.png">

**Todos**

- Move Kyma extensions, gulp extensions-related tasks etc to kyma-dashboard repo
- Adjust busola-deploy to pick up changes from kyma-dashboard/dev
- Add tests for all EXT components to pizzas

**Comment by Wawrzyn321** [comment]
Running e2e tests locally - there won't be Busola sources at kyma-dashboard, which means we need to:
- run Busola locally
- run Cypress tests in kyma-dashboard.

**Comment by valentinvieriu** [comment]
This was delivered.
