### ISSUE TITLE
Kyma Dashboard - Pod Logs not available

### ISSUE THREAD

**Issue by Mklarius001** [kyma-project/busola#2024]
**Description**

I am not able to see logs for any Pods in the Kyma UI on Google Chrome. This affects all clusters(prod/non-prod)/namespaces(test, dev, pilot, prod). 
Used versions: Kubernetes: v1.23.12; Kyma: 2.7.3

My assigned role is cluster-admin
A collegue with the same cluster-admin role is able to see the logs correctly, others have troubles as well.

Error message of the pod's logs:
![image](https://user-images.githubusercontent.com/110472759/201133181-2a2a96f6-c2f1-4d61-9762-1285d286266f.png)

Additionally I inspected the page with the browser's dev tools and discovered that the fetch request for the logs cancel after a while of being caught in pending state:

![image](https://user-images.githubusercontent.com/110472759/201134262-461b2dbf-c89a-4444-9cfa-f9c0a2496801.png)

printing the logs to the console works as intended.

**Expected result**

Correct Display of incoming logs for a specific time period

**Actual result**

see error image above

**Comment by valentinvieriu** [comment]
We cannot reproduce this scenario. Logs seems to work as expected
