### ISSUE TITLE
Application locks up on cluster connect (URL /cluster)

### ISSUE THREAD

**Issue by marwinski** [kyma-project/busola#2027]
**Description**

When I connect to a cluster by copying a kubeconfig file the application locks up with a "no route" error message. The reason appears to be that the cluster is in a private environment and there is no network connectivity to that environment.

**Expected result**

Application should print a meaningful error message and not lock up.

**Actual result**

Application locks up, needs complete reload.

**Steps to reproduce**

Copy kubeconfig of a private cluster and click "connect".

**Troubleshooting**

**Comment by valentinvieriu** [comment]
Thank you @marwinski . We indeed need the API server to be reachable by our app.
For situations when the k8s API is in a protected area, use our local dashboard.
You can run Busola as a docker image on your local machine, and then access a restricted api server

**Comment by marwinski** [comment]
Well @valentinvieriu this was obviously my fault but not the reason for the ticket. If the kube-apiserver is not reachable a meaningful error message should be printed and the application must not lock up.
