### ISSUE TITLE
Misleading documentation for Kyma Dashboard access

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#2050]
**Description**

I want to deploy Kyma on a fresh Gardener cluster and access Busola dashboard. I follow [installation guide](https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/02-install-kyma).  

I first provisioned new cluster on Gardener, then deployed kyma with `kyma deploy` command. According to the installation guide (section _[Default Installation](https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/02-install-kyma#default-installation)_)I should be able to access dashboard with the link: [https://dashboard.kyma-project.io/](https://dashboard.kyma-project.io/), but the page does not open.

**Expected result**

Documentation tells me how to access Kyma dashboard in a convenient way. I propose to [link](https://github.com/kyma-project/busola#busola-in-docker-adding-a-cluster-via-kubeconfig-id) to busola run with docker.

**Actual result**

I don't know how to access Kyma dashboard.

**Comment by valentinvieriu** [comment]
We should use the `kyma dashboard` command to open the dashboard
