### ISSUE TITLE
Function experience after 7902dcb7

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/busola#2053]
**Description**
After https://github.com/kyma-project/busola/commit/7902dcb7 deployed on SAP BTP (managed version of Kyma), the developer experience with inline Functions is not great.
The editor is slow and not convinient anymore.
API rule created from within the function doesn't populate name and service.
After a new function created, I need to wait until it is deployed before making any code changes. Otherwise it complains that I'm using an outdated resource.

**Expected result**

Smooth developer experience

**Actual result**

Slow and not well performing experience
**Steps to reproduce**

**Troubleshooting**

**Comment by valentinvieriu** [comment]
Thank you @VishnAndr . We are aware of this reduced user experience.
We decided to move all our views to Busola Extensions. This introduces a temporary reduction in functionality, but we plan on revisiting all the views and adding back the missing features.
