### ISSUE TITLE
Deploy new workload should have option to upload yaml

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/busola#206]
Within the Overview pane of a namespace the option to "Deploy new workload" only allows you to "Create Function" or "Create Deployment". There should be an option to "Upload YAML" matching what is currently in Kyma 1.x

**Comment by valentinvieriu** [comment]
You are correct, we do have this in our backlog, it is not so trivial as might sound.

**Comment by valentinvieriu** [comment]
I will close this issue in the favour of : https://github.com/kyma-project/busola/issues/861
