### ISSUE TITLE
Log view should default to newest first

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/busola#207]
Log view should default to newest first and indicate that it will auto refresh.

**Comment by valentinvieriu** [comment]
Thank you for the Feedback @jcawley5 
We planned on adding more features to the logs, reverse was one of them.


Let's add to this also

- [ ] Have the ability to slice the logs on a specific timeframe with predefined options, 1h, 3h, 6h, 1d, all
- [ ] Have the functionality to toggle the order - normal, reverse

![image](https://user-images.githubusercontent.com/478866/121492866-8c10e080-c9d7-11eb-8658-c49dede9cca8.png)

**Comment by Sawthis** [comment]
#234
