### ISSUE TITLE
Inconsistent information regarding valid characters in namespaces

### ISSUE THREAD

**Issue by efarrar** [kyma-project/busola#2122]
**Description**
When creating a namespace in the console, the UI hint says "The name must consist of lowercase alphanumeric characters, can contain '-' and '.' (e.g.: 'my.name-1').".

<img width="827" alt="create_namespace" src="https://user-images.githubusercontent.com/6874519/206265028-a5383130-a4a9-4b37-9a95-a9337930ded8.png">

I tried using a namespace with a period (specifically, 'my.name-1' which was provided as an example).

**Expected result**

I would expect the instance to be created.

**Actual result**

An error dialog appears that says "Namespace "my.name-1" is invalid. The error dialog includes the regex for validation which does not appear to allow periods.

<img width="792" alt="create_namespace_error" src="https://user-images.githubusercontent.com/6874519/206265057-097f5124-3009-4b36-9d1b-01dd93f4fc48.png">

**Steps to reproduce**

1. Open Kyma Console.
2. Go to namespaces.
3. Attempt to create a new namespace named 'my.name-1'.
4. Observe the error dialog.

**Troubleshooting**

I have worked around the issue by avoiding using periods.

**Comment by akucharska** [comment]
Will be fixed in https://github.com/kyma-project/busola/pull/2189/
