### ISSUE TITLE
Wrong handler sample used for python functions created from UI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#2125]
**Description**

When creating python function the handler sample from nodejs is used.

**Expected result**

When creating python function the handler sample from python should be used.

**Actual result**

When creating python function the handler sample from nodejs is used.

**Steps to reproduce**

Create function from UI and select python runtime

**Attachments**

![Screenshot 2022-12-08 at 09 21 08](https://user-images.githubusercontent.com/6783567/206395944-39630495-4cd2-42c5-8772-b7276244e93e.png)
![Screenshot 2022-12-08 at 09 22 02](https://user-images.githubusercontent.com/6783567/206395952-e7b75118-c228-4350-9572-3ba01bab04ac.png)

**Comment by dariadomagala** [comment]
Hi @kwiatekus, as a workaround, for now, you can switch languages using the top dropdown with the presets. We will handle the bug in the meanwhile.
