### ISSUE TITLE
Source lost in functions

### ISSUE THREAD

**Issue by qbalukom** [kyma-project/busola#2174]
**Description**

"spec.source" value is lost when switching from yaml to form.

**Expected result**

"Source" should be available when switching from yaml to form.

**Actual result**

"Source" field is empty when switching from yaml (switching back to yaml reveals it's empty).

**Steps to reproduce**

Go to functions. Make sure there's content in the "source field". Switch to "yaml" tab. Switch back. Source field is empty.

**Comment by valentinvieriu** [comment]
can we do something about the Dependency section too? It is empty and does not show the structure of a package.json
![image](https://user-images.githubusercontent.com/478866/207801983-0b260f96-3072-4e25-92a5-39ef45b904dc.png)
