### ISSUE TITLE
Extensibility: Setting tabs dynamically with the Tabs widget

### ISSUE THREAD

**Issue by tnykd** [kyma-project/busola#2209]
**Description**

The Tabs widget currently displays all tabs with names that must be specifically provided. This means you have to specify the exact name for each tab and describe the exact number of tabs you want. A nice improvement will be that you can choose to set also the tabs dynamically, like a template that will be filled for each tab.

**Reasons**

Our custom resources can have very long lists with double to triple digit entries, which are separated by specific name. So we want to have a separate tab based on the different separator name and in each tab to have a children widget which can be, for example, table, containing all the necessary information we want to expose.

**Comment by VaskoBozhurski** [comment]
/reopen
We still could use this feature. :)
