### ISSUE TITLE
Unexpected version of sidecars: expected v1beta1, got v1alpha3

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#2219]
**Description**
https://sentry.io/organizations/kyma-project/issues/3637500828/?project=5953495&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by Lyczeq** [comment]
I'm closing the issue due to the duplication https://github.com/kyma-project/busola/issues/2025
