### ISSUE TITLE
Create Namespace: istio-injection can not be set to enabled on Advanced tab

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/busola#2255]
Choose the option to create namespace
choose the tab advanced
Under Labels, delete the entry istio-injection
Try to enter in label again, it will be disabled right away

There also used to be a toggle on the Simple tab which allowed you to enable/disable this

**Comment by mrCherry97** [comment]
Hi @jcawley5 
changes are pushed on dev/stage/prod, so everything now should works fine, please doucle-check and if problem appears reopen the issue.

**Comment by jcawley5** [comment]
The simple tab looks good. One note about the Advanced tab, is it should not be listed under Annotations, but as a Label.
