### ISSUE TITLE
EXT: prepare multi-checkbox component

### ISSUE THREAD

**Issue by Julius-Schmidt** [kyma-project/busola#2283]
**Description**

As a user, I need a widget that can group multiple widgets together and get stored at the same path.
**Reasons**

**Attachments**

<img width="400" alt="Screenshot 2023-01-16 at 09 21 11" src="https://user-images.githubusercontent.com/118550912/212630497-b9b43249-8952-4552-8825-f8505a2ee852.png">

<img width="388" alt="Screenshot 2023-01-16 at 09 21 00" src="https://user-images.githubusercontent.com/118550912/212630489-6c46f667-c457-41cb-80a7-bbcc16673404.png">

**Comment by akucharska** [comment]
I propose doing a multi-checkbox component
