### ISSUE TITLE
Ext:  Variable values don't get stored

### ISSUE THREAD

**Issue by Julius-Schmidt** [kyma-project/busola#2302]
**Description**

If I try to store a variable by subscribing to it, it doesn't get stored, although the correct path is provided.

<img width="1394" alt="Screenshot 2023-01-23 at 12 12 42" src="https://user-images.githubusercontent.com/118550912/214026787-a53b3741-4af4-45b5-8267-39d2b549b568.png">
<img width="318" alt="Screenshot 2023-01-23 at 12 12 51" src="https://user-images.githubusercontent.com/118550912/214026817-6548a984-9cd9-49b4-9e98-47946633fd58.png">
<img width="554" alt="Screenshot 2023-01-23 at 12 13 19" src="https://user-images.githubusercontent.com/118550912/214026828-1fdf172d-e385-4d51-b8f4-dbb0747c293d.png">

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by akucharska** [comment]
Fixed in https://github.com/kyma-project/busola/pull/2304
