### ISSUE TITLE
Wrong Placeholder text in Dropdown Field

### ISSUE THREAD

**Issue by jalibu** [kyma-project/busola#2338]
**Description**
If you create a Service Binding, there is a Dropdown that asks for a Service Binding. But it is a Service Instance which is meant here.

![image](https://user-images.githubusercontent.com/25933231/216674967-d178a3ac-3cdd-4161-9df9-bef9ff38e095.png)

**Comment by Lyczeq** [comment]
This issue has already been fixed. 

![Image](https://user-images.githubusercontent.com/56163767/217250443-12fd4f7e-41d9-47f0-8df5-56f11ffbcd6d.png)
