### ISSUE TITLE
`SimpleList` does not allow text input in the `Simple` form.

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/busola#2369]
**Description**

In our extension, we [define a `SimpleList` for `Types`](https://github.com/kyma-project/kyma/blob/532d5443b9f032d97527c7ed1380f95720a19d3f/resources/eventing/charts/controller/templates/busola-extension.yaml#L73). But the form does not allow text input in the simple view:

![image](https://user-images.githubusercontent.com/58187735/221813240-3ef1eead-1b81-471c-a79f-77aee1a90a6e.png)

However, the advanced view does allow text input:

![image](https://user-images.githubusercontent.com/58187735/221814140-0a876efa-50f5-429f-90cf-862446e95f11.png)
 
and the value appear in the yaml:

![image](https://user-images.githubusercontent.com/58187735/221814812-9e3ab542-4da5-4091-86f4-69a791622a7b.png)

and in the simple view one can see that items have been added, but the values are not displayed:

![image](https://user-images.githubusercontent.com/58187735/221814986-f4ad267e-338f-4224-b154-a925d1ab1311.png)

this still does not allow text input, but deleting items from here will delete them for the other two views as well.

**Expected result**

Can enter and edit values in the simple view.

**Actual result**

Cannot enter and edit values in the simple view.

**Steps to reproduce**

**Troubleshooting**

**Comment by mrCherry97** [comment]
Hi @friedrichwilken ,
we provide some changes few weeks ago and you need to put `simple: true` in children too, so it will look like this:
```
    - path: spec.types
      simple: true
      widget: SimpleList
      defaultExpanded: true
      children:
        - path: '[]'
           simple: true
```
Please try it and if problem will appear one more time, please reopen an issue.
