### ISSUE TITLE
Subscription is rendered in wrong version in Function's edit form.

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/busola#2371]
**Description**

On the Function page, in the Subscription section, clicking on the edit button for the Subscription, the Subscription will be rendered as `v1alpha1` even though it is `v1alpha2`

![image](https://user-images.githubusercontent.com/58187735/222225390-a07f6469-524a-4d3b-8fb2-49135c9966ce.png)
vs
![image](https://user-images.githubusercontent.com/58187735/222225586-7e0cb4cf-dd55-4439-bf76-191081ab9a49.png)

```shell
 k get -n event-testing subscriptions.eventing.kyma-project.io wretched-variation -oyaml
apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  creationTimestamp: "2023-03-01T18:06:29Z"
  finalizers:
  - eventing.kyma-project.io
  generation: 1
  labels:
    app.kubernetes.io/name: wretched-variation
  name: wretched-variation
  namespace: event-testing
  resourceVersion: "27367"
  uid: 8095ede1-8480-4025-89f2-a6ae60daf6a3
spec:
  config:
    maxInFlightMessages: "10"
  sink: http://test.event-testing.svc.cluster.local
  source: ""
  typeMatching: exact
  types:
  - order.created
status:
  backend:
    types:
    - consumerName: e8e80fb1158a50e98181040a81accd35
      originalType: order.created
  conditions:
  - lastTransitionTime: "2023-03-01T18:06:30Z"
    reason: NATS Subscription active
    status: "True"
    type: Subscription active
  ready: true
  types:
  - cleanType: order.created
    originalType: order.created
```

**Expected result**

is rendered as `v1alpha2`

**Actual result**

is rendered as `v1alpha1`

**Steps to reproduce**

On a cluster from `main`
1. create namespace
2. create function
3. create subscription where `service` points to function.
4. go to function, config-tab
5. hit the edit button for the subscription

**Troubleshooting**

**Comment by mrCherry97** [comment]
We have hardcoded version of subscriptions, so if you want to have `v1alpha2` on your cluster, you need to deploy functions extension with changing this line to your version: https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/serverless/functions.yaml#L454 
And rather that, when v1alpha2 version will be released and all clients will be migrated to new version please change this and make a PR to `kyma-dashboard` or ping us to change that.
