### ISSUE TITLE
Undefined APIRule's host in the Service view

### ISSUE THREAD

**Issue by grego952** [kyma-project/busola#2461]
**Description**
I created and exposed the microservice according to this [tutorial](https://kyma-project.io/docs/kyma/latest/02-get-started/03-deploy-expose-microservice/). When I try to access my APIrule's host from the Service view, all I can see is that the host is undefined.

![Zrzut ekranu 2023-05-10 o 08 05 32](https://github.com/kyma-project/busola/assets/62639546/e772422e-95f1-4a61-94f9-10c2b633d7a0)

In the APIRule's view, everything works fine.

![image](https://github.com/kyma-project/busola/assets/62639546/1c59f09e-fff0-4492-a8b9-c86760725724)

**Expected result**
The user should be able to access the host from the Service view.

**Actual result**
The user cannot access the host from the Service view because there the host is `undefined`.

**Steps to reproduce**
https://kyma-project.io/docs/kyma/latest/02-get-started/03-deploy-expose-microservice/

**Troubleshooting**

**Comment by dbadura** [comment]
I tried to reproduce this bug. it seems to be fixed:
![image](https://github.com/kyma-project/busola/assets/45110612/d4e70816-adf6-4674-a90c-fb95e816c38a)

**Comment by mrCherry97** [comment]
@grego952 please double-check if the bug is not appearing anymore. If a bug appears one more time, please catch us up.

Thanks
