### ISSUE TITLE
Remove Create and Edit for Module templates

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2472]
**Description**

We should not have Create or Edit Module templates in the UI.

**Reasons**

Those resources should not be edited in the UI. This should be part of the submission process.

**Attachments**

**Comment by valentinvieriu** [comment]
@varbanv please confirm that this was our latest decision

**Comment by varbanv** [comment]
@valentinvieriu confirmed. As discussed and agreed during the PO meeting on May 15th 2023.

**Comment by mrCherry97** [comment]
Create and Edit disabled, changes pushed to the stage.
