### ISSUE TITLE
Display version of module on Kyma CR edit page

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#2476]
**Description**

I'd like to know what version of module is available in particular channel BEFORE I install the module. So that I can check the release notes / documentation before, to make a decision about installing module from one channel or the other.

Currently I am shown only module name and channel.

![image](https://github.com/kyma-project/busola/assets/69588692/1094be9a-1183-4bf9-93ac-05e9432b68da)

It would be good to display version of module in channel combo box item (if it can be styled in this way, clickable link to docs/release notes) or at least right after I selected particular channel, but before saved changes.

**Comment by a-thaler** [comment]
I think even more important is to get a summary of what that module is about with a link to the documentation. Still version is also relevant.

**Comment by valentinvieriu** [comment]
We will have a documentation link that will be visible to the user before he clicks on apply.
This deep link is controlled by Module Template. We can technically add the version also in the description.

@akucharska
