### ISSUE TITLE
Kyma resource edit - misleading / missing labels

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#2485]
1. Open Kyma resource in edit mode.
2. There are 2 example modules - Keda in Beta and BTP Operator a standard one. 
3. Both modules have documentation (e.g. properly liked on main page of Kyma resource)
4. **PROBLEM1:** Warning for beta module is displayed under BTP Operator module which is not beta. I can't find which module is beta using information displayed on that page.
5. **PROBLEM2:** Documentation link for BTP Operator is missing (it's probably replaced by the beta warning)

<img width="2008" alt="image" src="https://github.com/kyma-project/busola/assets/69588692/2a28913f-d24f-48aa-988c-cdc38a6efd93">

**Comment by mrCherry97** [comment]
@arturskorupa problem2 was fixed by previous changes, problem1 will be solved in mentioned PR.
