### ISSUE TITLE
Open modules section when entering Kyma resource edit mode

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#2486]
When entering Edit mode for Kyma resoruces It would be good to have modules section already open so that I can see what modules are installed and do the actions on them.

That's the most probable use case for editing Kyma resource - to enable / disable modules therefore it should be easily accessible.

**Comment by mrCherry97** [comment]
Resolved in https://github.com/kyma-project/kyma-dashboard/pull/204
