### ISSUE TITLE
Additional filter/sort options for pod list view

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/busola#2491]
**Description**
The resource list view in busola is a nice way to get an overview of the existing instances. However, it is hard to get the attention directed to the important things by having some important filters in place.
Example pod list view. A pod has a status which is of high interest, especially if the status is not running. There is no easy way to list the unhealthy pods. Or the pods having an increase in restarts. It will be good to have a way to filter by that fields or even to filter on that criterias.

Additionally, the namespace overview already outlines healthy/unhealthy pods in the first chart. Having a way to immediately jump to the unhealthy pods of a namespace using a deep link will simplify the flow.

Criterias:
- Have an easy way to get to the unhealthy pods in a namespace
- The list of pods should either be sorted by health and/or restarts or filtered to get an overview easy

**Reasons**
Simplification of flows when using busola on a daily base

**Attachments**

**Comment by mrCherry97** [comment]
Sorry for no updates, it's done.
You can sort by the status in `Pods`, in the future we plan to expand searching options for every resource.
![image](https://github.com/user-attachments/assets/c9b93f5e-f08a-43a0-89d8-16d5af069263)
