### ISSUE TITLE
Fix tests after changing gardener flow

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#2511]
**Description**
Gardener changed their flow, and currently, we are getting kubeconfig with multiconext which causes some problems in our test flow.

**Expected result**
Tests are working and passing.

**Actual result**
Tests are failing and they are commented.

**Tests**
- [ ] test-edit-cluster.spec.js
- [ ] test-login-kubeconfigID.spec.js -> Handles default kubeconfig
- [ ] test-other-login-options.spec.js -> Kubeconfig and token separately
- [ ] test-cluster-configuration.spec.js  -> Applies config from target cluster (session storage)

**Troubleshooting**

**Comment by mrCherry97** [comment]
No longer valid

**Comment by pbochynski** [comment]
Please remove unused tests and close the issue.
