### ISSUE TITLE
Hydra migration notification

### ISSUE THREAD

**Issue by strekm** [kyma-project/busola#2593]
**Description**

Implement pop up notification explaining that ORY Hydra and its components will be migrated to `hydra-deprecated` namespaces and it won't be maintained by Kyma anymore. This notification should contain link to existing blogpost on how to migrate existing workloads secured with token issued by Hydra to SAP Cloud Identity Services. Hydra removal is planned for Kyma 2.19 that is planned for rollout to managed offering on 14.10. Notification should pop up only on clusters that have any oauth2clients created.

**Reasons**

ORY Hydra removal

**Attachments**
https://blogs.sap.com/2023/06/06/sap-btp-kyma-runtime-ory-hydra-oauth2-client-migration/

**Comment by valentinvieriu** [comment]
Please submit a PR to https://github.com/kyma-project/kyma-dashboard/ you can have a look on how we implemented https://github.com/kyma-project/kyma-dashboard/blob/main/extensions/kyma/kyma.yaml#L133 using [widget-injections](https://github.com/kyma-project/busola/blob/main/docs/extensibility/display-section.md#widget-injections-overview)

**Comment by strekm** [comment]
moved https://github.com/kyma-project/kyma-dashboard/issues/226
