### ISSUE TITLE
Default name of the create NATS module CR button is rendered wrong

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/busola#2595]
**Description**

Default name of the create NATS module CR button is rendered wrong (see attached).

**Expected results**

The button label should say "Create NATS".

**Actual results**

The button label says "Create NAT".

![busola-bug-0](https://github.com/kyma-project/busola/assets/24314423/35c32da6-1eb4-45b5-89d3-537c1d6d7bf5)
![busola-bug-1](https://github.com/kyma-project/busola/assets/24314423/8142a0a0-a2a0-413b-aeb0-934043aba1e4)

**Comment by mrCherry97** [comment]
No longer valid, product standards says that there should be only `Create`.
