### ISSUE TITLE
Busola Breaks on refresh

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2619]
**Description**

Left navigation breaks on refresh

**Expected result**

The navigation should remain the same

**Actual result**

<img width="287" alt="image" src="https://github.com/kyma-project/busola/assets/478866/f5d955aa-542b-4205-b0d2-5f944d8e8f06">

**Steps to reproduce**

- Click on a link to load Kyma Dashboard
- mc+r ( to refresh the page )

**Comment by mrCherry97** [comment]
problem is only on safari, after merging UI5 this problem should be fixed.
