### ISSUE TITLE
Deep Links to Kyma Dashboard

### ISSUE THREAD

**Issue by dzett** [kyma-project/busola#2632]
**Description**

When I store a deep link to the Kyma Dashboard (say, a namespace inside my cluster) by copying the URL shown in the browser at that time, the link doesn't work when used in a clear browser session.

Example: A link of this form, as copied from the browser location while showing namespace "mynamespace":

https://dashboard.kyma.cloud/cluster/shoot--kyma--c-3537abc/namespaces/mynamespace/ 

does not work when called in a clean browser window.

I fiddled around and by manually concatenating it like this:

https://dashboard.kyma.cloud/cluster/shoot--kyma--c-3537abc/namespaces/mynamespace/?kubeconfigID=ABBAABBA-1234-5678-ABCD-123456789ABC

it works as a deep link which passed through the SSO flow etc. and in the end leads to the selected namespace.

Is there a reason why the Browser location can't show a link that is bookmarkable / copyable? This would be my feature request.

**Reasons**

I expect many users frequently working with Kyma will want to have their deep links to where they work stored. I spoke to three colleagues and none of them knew how to store a deep link. At least there should be a clear documentation that leads the user to the above "hack", assuming this concatenation of the kubeconfigID is a stable behavior.

Thanks for looking into this!

**Comment by dzett** [comment]
Hi there, can you please provide some reaction? Is there a problem with reproducing this? Thanks, D.

**Comment by valentinvieriu** [comment]
Sorry for the late reaction @dzett and thank you for the feature request. Indeed if you need a deep link to your dashboard, you should bookmark the link with KubeconfigID.
There is another solution that will work, but this will require that you add the kubeconfig file manually, and then choose to persist it in LocalStorage. Using this approach, next time when you open the same browser, you will have the kubeconfig already added, and you can use bookmark the deep links.
 
<img width="1413" alt="image" src="https://github.com/kyma-project/busola/assets/478866/463af8d4-4a94-4120-93cf-f9b460fc777e">

As Kyma Dashboard is stateless, it's very hard to solve this problem differently.

You can always get the deep link to your cluster from the BTP Cockpit ( assuming that you are using BTP-hosted Kyma ). KubeconfigID "hack" is an implementation detail that might change in the future.

**Comment by valentinvieriu** [comment]
@dzett I will close this issue, as there is a way to consistently get the deep link to your cluster from the BTP Cockpit

<img width="607" alt="image" src="https://github.com/kyma-project/busola/assets/478866/5970d889-b292-4861-a46e-a7fd70fdedc2">
