### ISSUE TITLE
kyma-system namespace not found in API Rule Creation

### ISSUE THREAD

**Issue by absqwe** [kyma-project/busola#2634]
**Description**

- Go to API Rules
- Create new API Rule
- In Gateway section, namespace "kyma-system" is markdown as red
- When clicked to namespace dropdown, kyma-system is not found
- If not clicked on dropdown, API Rule creation is still allowed, endpoint works with no issues. 

![kyma-api-rule](https://github.com/kyma-project/busola/assets/104209662/9e75d557-c637-44d2-b9fb-e4e4eeebf3e8)

**Comment by dbadura** [comment]
Hello,
I couldn't reproduce the issue.
