### ISSUE TITLE
CPU quota not presented on namespace overview

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#2641]
On the Namespace's Overview page there is a section presenting the quota object. Despite the fact both quotas, for CPU and Memory are set, the page shows only the Memory quota.

<img width="622" alt="image" src="https://github.com/kyma-project/busola/assets/69588692/49c80922-af85-4f1a-9f40-43f062763d52">

Proposed solution:
- display CPU quota below the memory

**Comment by valentinvieriu** [comment]
Please fix this in https://github.com/kyma-project/busola/issues/2653
