### ISSUE TITLE
Redesigning List Items for Responsive Layout in Busola Dashboard

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2654]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Matthew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer), I would like to see the list items in Busola Dashboard redesigned to be responsive and follow the design recommendations from [Figma](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=7619%3A94332&mode=design&t=Bp37w1J6b3QZRAan-1), so that I can have a seamless and efficient user experience on devices with different viewport sizes.

**Acceptance Criteria**
- [ ] List items are redesigned to be responsive, adapting their layout based on the viewport size.
- [ ] Design follows the guidelines and recommendations provided in the Figma design.
- [ ] Reduced amount of information is displayed for smaller viewports, without compromising essential details.
- [ ] Label positioning is optimized for readability and accessibility across different device sizes.
- [ ] Integration with the context of [Epic 2621](https://github.com/kyma-project/busola/issues/2621) to ensure consistency and relevance.

**Business Value**

This improvement will enhance the user experience for both Sebastian and Matthew by providing a more adaptable, readable, and efficient interface, especially when accessing the Busola Dashboard on devices with varying screen sizes.

**Reasons**

Implementing this feature will align with modern UI/UX standards for responsive design, catering to the diverse range of devices used by cloud-native engineers and enterprise architects. It ensures that the information hierarchy and accessibility are maintained across different viewing contexts.

**Dependencies**

- Alignment with the broader redesign efforts as outlined in [Epic 2621](https://github.com/kyma-project/busola/issues/2621).
- Collaboration with the design team for adherence to the Figma design specifications.

**Non-functional Requirements**

- Performance: Ensure that the redesign does not adversely affect the dashboard's performance.
- Accessibility: Adherence to accessibility standards for users with different abilities.
- Scalability: Design should be scalable for future additions or modifications preparing for the three column layout that we will about to implement

**Notes and Comments**

Further discussions around this feature should consider the evolving needs of both our personas, Matthew and Sebastian, ensuring that the redesign addresses their daily operational challenges effectively.

**Size or Effort**

This is a medium-sized effort, requiring close collaboration between the development and design teams to implement and test the responsiveness of the redesign.

**Mockups or Diagrams**

Refer to the [Figma design](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=7619%3A94332&mode=design&t=Bp37w1J6b3QZRAan-1) for mockups and diagrams.

**Useful Links**

- [Epic 2621](https://github.com/kyma-project/busola/issues/2621) for overall context and background.
- [Figma Redesign & Modules](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=7619%3A94332&mode=design&t=Bp37w1J6b3QZRAan-1) for design specifications.

**Attachments**

<img width="1124" alt="image" src="https://github.com/kyma-project/busola/assets/478866/8b103c32-e36a-4f66-97b2-b057f51da7bb">
<img width="460" alt="image" src="https://github.com/kyma-project/busola/assets/478866/de034719-7658-4e63-add2-710f3baa46d2">

**Comment by mrCherry97** [comment]
we can use "normal" `Table` component, but they need to fix the bug with selecting row
https://github.com/SAP/ui5-webcomponents/issues/8203

**Comment by mrCherry97** [comment]
Show more on labels will be make as follow-up, because it's more complex topic, here is draft PR with some thoughts: https://github.com/kyma-project/busola/pull/2759

**Comment by mrCherry97** [comment]
For arrow, UI5 has issue opened: https://github.com/SAP/ui5-webcomponents/issues/4538

**Comment by mrCherry97** [comment]
Search should be changed from combobox to input, will be made as followup: https://github.com/kyma-project/busola/issues/2771

**Comment by mrCherry97** [comment]
Follow-up issue for Labels and show more: https://github.com/kyma-project/busola/issues/2772
