### ISSUE TITLE
SPIKE: Assessing Feasibility of a 4-Column Layout in Busola Dashboard

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2660]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Mathew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer), we would like to explore the introduction of a 4-column layout in the Busola Dashboard (referencing [Epic #2621](https://github.com/kyma-project/busola/issues/2621)) to enhance user experience in terms of navigation and information display.

**Acceptance Criteria**
- [x] Analysis of the implementation feasibility for a 4-column layout, considering the existing Busola architecture.
- [x] Evaluation of responsive behavior for the new layout.
- [ ] Assessment of deep link functionality integration with the new layout.
- [ ] Provision of a detailed report splitting the large user story into smaller, deliverable tasks.
- [ ] Review of the Figma design file and suggestions for layout adjustments if necessary.

**Business Value**

The introduction of a 4-column layout would streamline user navigation and enhance the overall user experience, especially for users like Matthew and Sebastian who require efficient and flexible tools for their Kubernetes environment management.

**Reasons**

This SPIKE is necessary to understand the complexities involved in transitioning from the current layout to a more efficient 4-column layout, ensuring that the new design meets both technical feasibility and user experience standards.

**Dependencies**

This SPIKE depends on the existing architecture of the Busola Dashboard and the user feedback gathered in [Epic #2621](https://github.com/kyma-project/busola/issues/2621).

**Non-functional Requirements**

- The new layout must maintain or improve the current performance standards of Busola.
- It should be responsive, adapting to different screen sizes without losing functionality. If screen is to small we have the oportunity to colapse the left navigation to allow more space for the columns
- The implementation should not disrupt existing deep link capabilities. The deep link will always point to the detail page of the resource. we will evaluate if there is a way to capture the navigation tree so that we can display the 3/4 column design

**Notes and Comments**

Discussion regarding the feasibility and potential challenges of the 4-column layout is crucial before any development begins. This will ensure a smooth transition and effective implementation.

**Size or Effort**

This SPIKE will require extensive analysis and should be given ample time for thorough evaluation. A time frame will be established after preliminary assessment.

**Mockups or Diagrams**

Reference to Figma File for designs and layout: [Figma Redesign & Modules](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=7619%3A95212&mode=design&t=Bp37w1J6b3QZRAan-1)

**Useful Links**

- [Epic #2621](https://github.com/kyma-project/busola/issues/2621)
- [Busola GitHub Repository](https://github.com/kyma-project/busola)

**Attachments**

<img width="1214" alt="image" src="https://github.com/kyma-project/busola/assets/478866/8064274d-2c2e-4e16-8adf-c2a46255e591">
<img width="1154" alt="image" src="https://github.com/kyma-project/busola/assets/478866/db9426fc-b5aa-41f5-892c-42afddb143f3">

**Comment by mrCherry97** [comment]
- [ ] prepare wrapper for flexibleColumnLayout
   - [ ] ResourceList as startingColumen (adjust Table to open middleColumn)
   - [ ] ResourceDetails as middleColumn (adjust custom Resources view to open and column)
   - [ ] ResourceDetails as endColumn
- [ ] adjust action buttons in DynamicPageHeader (close and full screen)

**Comment by mrCherry97** [comment]
- [ ] extensibility adjustments
- [ ] column opening from the left side on CR @mrCherry97 
- [ ] opening column is lagging on some views 
- [ ] URL -> set and get informations using query about layout, displayed columns, etc @akucharska 
- [ ] URL is not changing after closing column
- [ ] details of 3 column are not rendered properly on CR @mrCherry97 
- [ ] adjust tests
