### ISSUE TITLE
Redesign of Resource Graph for Busola Dashboard

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2662]
**Description**

As [Sebastian](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#sebastian---tech-lead) and [Matthew](https://github.com/kyma-project/community/blob/main/manifesto/personas.md#matthew---cloud-native-software-engineer), we would like the Resource Graph in the Busola Dashboard to be redesigned in accordance with the SAP Horizon Visual Theme to enhance user experience and visual consistency across the platform.

**Acceptance Criteria**
- [ ] Redesign the Resource Graph according to the specifications in the Figma file.
- [ ] Implement the Horizon Theme's color palette and design elements in the Resource Graph.
- [ ] Ensure high contrast and readability in the new design.
- [ ] Make sure it works in dark mode

**Business Value**

This enhancement will provide a more consistent and visually appealing user experience that aligns with SAP standards, improving usability and satisfaction for cloud-native engineers and enterprise architects.

**Reasons**

Redesigning the Resource Graph is important for maintaining a cohesive look and feel throughout the Busola Dashboard, adhering to SAP's visual guidelines, and meeting the expectations of our sophisticated user base.

**Dependencies**

Depends on the broader initiative to align Busola with SAP's Horizon Visual Theme using UI5 Web Components.

**Non-functional Requirements**

The redesign should maintain or improve the current performance and responsiveness of the Resource Graph.

**Notes and Comments**

Refer to the broader Epic for additional context: [Align Busola with SAP's Horizon Visual Theme](https://github.com/kyma-project/busola/issues/2621).

**Size or Effort**

Small - Requires detailed design and development effort, but within the scope of the existing project framework.

**Mockups or Diagrams**

Refer to the Figma file for detailed design and layout specifications.

**Useful Links**

- [Epic for Horizon Visual Theme](https://github.com/kyma-project/busola/issues/2621)
- [Figma Design File](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=7619%3A95212&mode=design&t=Bp37w1J6b3QZRAan-1)

**Attachments**

<img width="1829" alt="image" src="https://github.com/kyma-project/busola/assets/478866/34d8827b-125d-4e27-ba8e-865b303495ca">

**Comment by dbadura** [comment]
As network graph is not available in react componetns I created feature request: https://github.com/SAP/ui5-webcomponents-react/issues/5370

**Comment by mrCherry97** [comment]
UI5 team, don't have time to deliver the graph feature.
