### ISSUE TITLE
Combo boxes on edit view do not work on Safari

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2670]
**Description**

**Expected result**

Combo boxes should open

**Actual result**

Combo boxes are closed automatically

**Steps to reproduce**

Use latest Safari on Mac. And try to create or edit a resource

**Troubleshooting**

https://github.com/kyma-project/busola/assets/478866/b4033429-d80e-4ecf-b2fb-c07454c314c5

**Comment by mrCherry97** [comment]
Potentially it will be fixed with https://github.com/kyma-project/busola/issues/2661

**Comment by mrCherry97** [comment]
Can't reproduce.
