### ISSUE TITLE
Empty 3 dots menu in the API Rule

### ISSUE THREAD

**Issue by marco-porru** [kyma-project/busola#2677]
**Description**

While opening APIRule screen and opening an existing API rule, a 3 dots menu appears in the **Rules** area and in the **Access Strategies** area. This menu is empty.

<img width="1466" alt="Screenshot 2023-12-05 at 14 52 01" src="https://github.com/kyma-project/busola/assets/57440567/c489ad24-87ac-462b-9f4e-a3bbfd31bf02">

**Expected result**

No 3 dots menu or menu filled with relevant data

**Actual result**

Empty menu

**Steps to reproduce**

Create any API Rule, navigate to it

**Troubleshooting**

Ignore it.

**Comment by valentinvieriu** [comment]
We do plan to use the 3 dots menu in the future, but for now indeed that functionality is not there. We will remove it until we have the feature.

Thank you for the issue
