### ISSUE TITLE
Unified the way we display tooltips

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#270]
**Description**

We need to use just one way of displaying tooltips. See recommended option in screenshots.

**Reasons**

UX needs to be consistent so that users does not get confused

**.Acceptance Criteria**

- [x] All input fields are checked, and we use the recommended ui display delay 1.5-2sec with the help insights
- [x] We remove all the info icons and ? icons
- [x] If the help content is too long for a tooltip or with deep expert information we need to identify and capture those sections and work with a TW to reduce the size

**Attachments**

![image](https://user-images.githubusercontent.com/478866/124720190-2ea17e00-df08-11eb-87c4-0bd7e536e9e6.png)

**Comment by Sawthis** [comment]
Please add tooltip for inactive Expose Function button.

**Comment by Sawthis** [comment]
https://github.com/kyma-project/busola/pull/297
