### ISSUE TITLE
Display Timestamp in Dashboard

### ISSUE THREAD

**Issue by henri-kohlberg** [kyma-project/busola#2714]
**Description**

The Kyma dashboard shows only the date for timestamps but does not show the time itself. This makes analyzing issues difficult. I am not aware of any way to view the exact times of a certain timestamp in the dashboard and have to use kubectl to see exact timestamps which is cumbersome.

Ideas:
- Always show the exact time instead of just the date
- Show exact time on hover over date
- Introduce condensed and wide mode to switch between displaying only the date or the full date + time
- Introduce a toggle whether only the date or full time should be shown

I am not totally sure whether this is a regression. I just noticed this issue since the latest Fiori theme updates and think that we could see exact times in the dashboard before. We are using managed Kyma 2.20.0 on SAP BTP with the "Light / Dark" theme.

**Reasons**

Having the exact time available is really useful for analyzing issues. The date is not sufficient e.g. to determine in which order events occurred. I miss this feature especially for events (on cluster and resource level) and for the "Created At" for any K8s resource. There are probably many other places where the time is missing.

**Attachments**

![image](https://github.com/kyma-project/busola/assets/144915566/ee949bd3-afea-4746-af8a-1186bc4b7a85)

![image](https://github.com/kyma-project/busola/assets/144915566/a8d807f4-95e6-4081-a669-a26b9e726953)

**Comment by valentinvieriu** [comment]
Thank you for your feature request @henri-kohlberg . We will prioritize this in our backlog. We had a major ui change ( moving to a new Theme ) and some fields need adjustments.
