### ISSUE TITLE
Adjust Monitoring And Health Widgets to follow the guidelines

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2744]
**Description**

**Expected result**

- The Cards should be fixed width, not responsive. 
- Empty space will be allowed to right.
- For small cards we should look into using analytical card as a base
- the 3 dots menu is not needed for now
- Implement the deep link. When a card has deep link Learn more is present. Adjust the cards that can have deep links.

**Actual result**

**Steps to reproduce**

**Troubleshooting**

<img width="1352" alt="image" src="https://github.com/kyma-project/busola/assets/478866/a54eacca-9442-4a12-b5a3-35dadc7fdf0c">

**Comment by mrCherry97** [comment]
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticalcard--docs
