### ISSUE TITLE
Labels should be displayed only in two rows

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#2772]
**Description**
UX request is to display only 2 rows of the labels on List and Details, if there are more labels `Show X more` should be displayed with the number of hidden labels. After clicking `show X more` the rest of the labels should be displayed.

**Reasons**
UX request.

**Acceptance criteria**
- [ ] labels are shown only in 2 rows
- [ ] show more links are displayed with the number of hidden labels
- [ ] clicking Show More is displaying all of the labels
- [ ] After clicking Show More, the action link should change to show less
- [ ] clicking show less is hiding more than 2 rows of labels 

**Attachments**
- [Figma designs](https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=7900-18217&mode=design&t=Ep4H42zOBbLYL9ML-0)
- [first thoughts PR](https://github.com/kyma-project/busola/pull/2759)

**Comment by dbadura** [comment]
The same solution should be applied to annotations.

**Comment by mrCherry97** [comment]
Currently it's blocked by: https://github.com/kyma-project/busola/issues/2654

**Comment by mrCherry97** [comment]
Labels are removed, no longer valid.
