### ISSUE TITLE
Clusters overview - Edit cluster - Update button disabled

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#2800]
**Description**

1. Go to clusters overview page
2. Open cluster for edit
3. Update button is disabled
4. Close the popup
5. Open again edit popup
6. Now update button is enabled
7. On every next attempt it stays enabled as expected

**Comment by mrCherry97** [comment]
hi @arturskorupa please double check if this issue is valid. We have a quick look and looks like it's fixed out of the box. 
Thanks in advance for update.

**Comment by arturskorupa** [comment]
I confirm the issue doesn't exist any more. Thanks
