### ISSUE TITLE
Provide information about resources reserved for nodes

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/busola#2817]
### Description

Many a times user are unclear about costs and do not understand why they have so many nodes provisioned in their Kyma cluster.
Provide transparency by showing node details and how man resources reserved.

one can see this with 

`kubectl describe nodes`

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests          Limits
  --------           --------          ------
  cpu                2777m (70%)       23944m (610%)
  memory             6747176390 (43%)  42765339536 (274%)
  ephemeral-storage  0 (0%)            0 (0%)
  hugepages-1Gi      0 (0%)            0 (0%)
  hugepages-2Mi      0 (0%)            0 (0%)
```

Perhaps display it as a pie chart / circle with reserver percentage or something similar

**Comment by dbadura** [comment]
Please also review and adjust node view in similar fashion like it's done in https://github.com/kyma-project/busola/issues/2857
