### ISSUE TITLE
[Test Case] - Perform Get Started guide on Firefox and Safari

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/busola#282]
**Summary**

Perform [Get Started guide](https://kyma-project.io/docs/kyma/latest/02-get-started/) for Busola on Firefox and Safari. 

**Prerequisites**
 - access to Busola
 
**Environment**
Kyma runtime

**Test Steps**
Perform [Get Started guide](https://kyma-project.io/docs/kyma/latest/02-get-started/) in Busola.
 
**Automation**
- Cypress doesn't work well with iframes on Firefox. Luigi supports webcomponents instead of iframes (possible solution).
- Safari is *not* supported by Cypress.

**Comment by dariadomagala** [comment]
I'd say we should also test Busola both with just kubeconfig and using init parameters. At least checking inf the navigation has been rendered as expected.

**Comment by Sawthis** [comment]
@dariadomagala is it not enough to test it with Cypress tests for Chrome?

**Comment by dariadomagala** [comment]
It's the part that if there's something wrong with it, then it could cause Busola totally unusable as it would fail before it even starts.
In my opinion, it's not too much additional work so maybe it would be worth testing _just in case_.
