### ISSUE TITLE
UX adjustments - resource edit

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#2841]
**Description**
- [x] Buttons hide and search need to be disabled in form view spec (This has been changed now, but I can see that if I switch to YAML they stay enabled and don’t become disabled anymore)
- [x] Bugged hover and toggled states for panel header buttons Please use standard Fiori buttons for this.
- [x] No need for two tooltips for panel header buttons, the browser has one by default

**Reasons**

**Attachments**
![Screenshot 2024-03-19 at 14 42 36](https://github.com/kyma-project/busola/assets/20790348/3d828cc5-0177-4760-840d-9bf8403571d5)
![Screenshot 2024-03-19 at 14 42 59](https://github.com/kyma-project/busola/assets/20790348/6522556f-43f5-47ae-97c1-251ad6a004ce)

Epic: https://github.com/kyma-project/busola/issues/2623

**Comment by OliwiaGowor** [comment]
fixed in https://github.com/kyma-project/busola/pull/2832
