### ISSUE TITLE
UX adjustment - info button

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#2842]
**Description**
- [x] We should use buttons for the info icons, so that they also come with their own padding and states: hover, pressed, etc
- [x] Clicking on this should open a popover with info, not a tooltip never use tooltips for displaying important information
- [x] The icon should be next to the input field (it is done but please validate)
- [x] In some forms we saw that an icon with a “?” inside was used, the only correct one is this one with the “i”

**Reasons**

**Attachments**
![Screenshot 2024-03-19 at 14 45 15](https://github.com/kyma-project/busola/assets/20790348/5b65c90f-0152-4f36-ada2-c777b2aafbd6)

Epic: https://github.com/kyma-project/busola/issues/2623

**Comment by OliwiaGowor** [comment]
fixed in https://github.com/kyma-project/busola/pull/2832
