### ISSUE TITLE
Upload Yaml looks broken

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2845]
- [ ] adjust margins and padding to look like on add cluster wizard
- [ ] use the wizard look and feel as a reference. 

![Image](https://github.com/kyma-project/busola/assets/478866/bd779498-f346-4bed-aa43-9e658f7ad3eb)

**Comment by dbadura** [comment]
Here is the design review: https://www.figma.com/file/AkzF9I1INdwc5iUtm5fKNU/Redesign-%26-Modules?type=design&node-id=11043-29676&mode=design
