### ISSUE TITLE
Spike: Kyma Companion UI Implementation in Kyma Dashboard

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#2849]
## Description

The Kyma Companion UI aims to enhance user interaction within the Kyma Dashboard by integrating a chat interface that provides context-sensitive help and general assistance. Leveraging design recommendations from a Figma file, this spike seeks to explore the feasibility, challenges, and optimal architecture for implementing the UI, ensuring seamless integration with backend services using the OPEN AI API format.

## Goal

- Assess the practicality of implementing the Kyma Companion UI as per Figma design specifications.
- Identify challenges in UI development and interaction with the backend.
- Determine the best architecture for backend communication, focusing on compatibility with the OPEN AI API format.
- Prototype context-sensitive and menu-triggered chat interface functionalities.

### Included
- Analysis of the Figma design file for UI requirements.
- Evaluation of frontend technologies for implementing the chat interface.
- Investigation into backend communication strategies, emphasizing the OPEN AI API format.
- Prototyping key components of the UI, including contextual triggering and markdown support in chat messages.

### Excluded
- Full-scale development of the Kyma Companion UI.
- Integration with other systems outside the Kyma ecosystem.
- Detailed user experience (UX) beyond the scope of the initial design recommendations.

## Acceptance Criteria

- Demonstration of a viable prototype that aligns with the Figma design recommendations.
- Identification of major challenges in UI development and backend integration.
- A proposed architecture for communicating with the backend using the OPEN AI API format.
- A set of recommendations for addressing identified challenges and proceeding with development.

## Time-box

This spike is allocated 4 weeks, allowing for thorough investigation and prototyping.

## Expected Outcome

- A prototype of the Kyma Companion UI demonstrating feasibility and design alignment.
- The prototype runs on Kyma AI Force Cluster and connects with the Kyma Companion Module 
- A comprehensive report detailing:
  - The feasibility of the UI implementation.
  - Identified challenges and potential solutions.
  - Recommended architecture for backend communication.
  - Suggestions for next steps in development based on the spike findings.

## Suggested Diagram for communications with Kyma Companion Module

```mermaid
sequenceDiagram
    participant U as User
    participant KCF as Kyma Companion Frontend
    participant KCM as Kyma Companion Module

    Note over U,KCF: User is viewing specific cluster resources
    U->>+KCF: Opens Kyma Companion App
    KCF->>+KCM: GET /initial-questions {context}
    Note over KCM: Context is current user view/resources
    KCM-->>-KCF: Returns initial questions based on context
    U->>+KCF: Selects a question
    Note over KCF: User interaction triggers query
    KCF->>+KCM: POST /chat {selected question}
    KCM-->>-KCF: Responds to user's query
    Note over KCF,KCM: Immediate follow-up action
    KCF->>+KCM: GET /follow-up-questions
    Note over KCM: Suggests next possible questions
    KCM-->>-KCF: Provides follow-up questions

```

## Links

- [Figma Desings](https://www.figma.com/file/Krpx9M0Vrc2ELIq7xLXIiA/Generative-AI?type=design&node-id=1-3&mode=design&t=lf5ckvoabZxo1MRl-0)

![image](https://github.com/kyma-project/busola/assets/478866/4dc2ec0b-47c7-4b8e-9739-ccfd617ebe4b)
![image](https://github.com/kyma-project/busola/assets/478866/e3e4b6e9-5a09-46ff-bf09-16ace2da3c1c)
![image](https://github.com/kyma-project/busola/assets/478866/39dcf4d4-9c38-47b3-a10d-5e2809219d2d)
![image](https://github.com/kyma-project/busola/assets/478866/69d55e27-f77a-4113-a477-de350add3e53)
![image](https://github.com/kyma-project/busola/assets/478866/425a4d79-bf83-4522-a883-55b3f5f8a45e)
![image](https://github.com/kyma-project/busola/assets/478866/9d68d694-7351-46d7-a1bb-7bff3da51552)
---
![image](https://github.com/kyma-project/busola/assets/478866/5a6d21e0-fd49-4a06-9c3e-7d14ad82ea6b)

**Comment by chriskari** [comment]
- [ ] error handling on first prompt should give the option to retry
- [ ] initial-suggestions-API-calls should depend on current pageType, namespace, nodeName
- [ ] close assistant on URL-/pageType changes
- [ ] further markdown formatting of responses ?
- [ ] adjust dark-mode and other themes
- [ ] use inner-cluster-API endpoints
