### ISSUE TITLE
Cannot edit nodejs function dependencies in json format

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#2854]
**Description**

Editing node.js function dependencies in a json format via kyma ui results in validation error

**Expected result**

I should be able edit dependencies using json format

**Actual result**

![Screenshot 2024-03-22 at 11 18 56](https://github.com/kyma-project/busola/assets/6783567/c0b6632f-723f-4537-9805-0029844d5761)
![Screenshot 2024-03-22 at 11 16 25](https://github.com/kyma-project/busola/assets/6783567/9b342126-f9fd-45fe-abee-6fcbb3f8994e)

**Steps to reproduce**

**Troubleshooting**
I tried with string with special characters and it worked.. but should not be this way, right?
`{\n  \"name\": \"tst\",\n  \"version\": \"0.0.1\",\n  \"dependencies\": {\n    \"axios\": \"^1.6.8\"\n  }\n}`

**Comment by mrCherry97** [comment]
hi @kwiatekus 
Fix is merged, we are planning PROD release around 02.04., so, for now, it will be available on dev and stage soon.

Best regards
Mateusz
