### ISSUE TITLE
Module management panel is missing

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#2858]
**Description**

I opened a cluster in Busola (from SKR), on landing page Module management section is not displayed any more.
I can still manage modules but it's very inconvenient (need to open kyma-system ns, then do several clicks to edit Kyma CR).  

**Expected result**

Module management panel is displayed on landing page.

**Comment by arturskorupa** [comment]
The problem was caused because I closed module management section by "x" and this information is kept in local storage.
It should be somehow possible to restore the closed banner otherwise I can't open it for any other cluster on the landscape.

**Comment by valentinvieriu** [comment]
it works as intended. We will not have the modules on the landing page anymore
