### ISSUE TITLE
 Custom resources with mixed case urlPath are not working properly

### ISSUE THREAD

**Issue by OliwiaGowor** [kyma-project/busola#2873]
**Description**
When a Custom Resource has a mixed case letters in the `urlPath` it causes bugs after trying to close column with resource details. It also causes bug when user has second column with details open and refreshes the page.

**Expected result**
Closing the second column with resource details works properly. Also user is able to refresh the page when second column with details is open and it loads properly.

**Actual result**
The page goes white after trying to close column with resource details. It also happens when user has second column with details open and refreshes the page.

**Steps to reproduce**
Find or create Custom resource with mixed case letters in the `urlPath`, go to the resource list. Open second column with details and try to close it or refresh the page.

**Troubleshooting**
Resource type in the URL is being changed to all lowercase letters after selecting the resource and it's no longer able to find that resource.

**Comment by mrCherry97** [comment]
Can't reproduce.
