### ISSUE TITLE
Create custom resources sometimes doesn't load schema

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#2892]
**Description**
Sometimes when clicking on the Custom resources -> some existing custom resource and then clicking on the create button to create a new custom resource, the following error: "Monaco autocompletion unavailable. Error: Resource schema not found." appears in the yaml tab.

**Expected result**

**Actual result**

**Steps to reproduce**
Custom resources -> some existing custom resource and then clicking on the create button to create a new custom resource -> YAML tab
<img width="1721" alt="Screenshot 2024-04-12 at 15 41 23" src="https://github.com/kyma-project/busola/assets/20790348/48f6d841-8e28-4387-b3b7-891ecfa3b3e6">

https://github.com/kyma-project/busola/assets/20790348/c5877fa2-9353-4ed8-8981-615140c9e35d

https://github.com/kyma-project/busola/assets/20790348/36a59d87-272f-4e3a-b336-c534063c5db2

**Troubleshooting**

**Comment by OliwiaGowor** [comment]
resolved in https://github.com/kyma-project/busola/pull/2899
