### ISSUE TITLE
Adjust Horizontal Pod Autoscaler

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#2916]
**Description**

Unify HPA metadata status, overview, events, resource graph.

**Acceptance Criteria**

Metadata
- [x] Status -> move to status card

Status
- [x] conditions
- [x] currentMetrics
- [x] currentReplicas
- [x] desiredReplicas
- [x] lastScaleTime

Overview card
- [ ] We might show some replicas count (currentReplicas / desiredReplicas)

Events are OK

Resource Graph is missing

**Reasons**
A comprehensive review and enhancement of Busola's Views will ensure that users have all necessary information and tools at their fingertips, promoting efficiency and reducing the potential for errors.

**Attachments**

**Useful Links**
Epic: https://github.com/kyma-project/busola/issues/2857
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#horizontalpodautoscaler-v2-autoscaling

**Comment by mrCherry97** [comment]
kyma-dashboard
