### ISSUE TITLE
Find out how to change "No ... " texts in Busola

### ISSUE THREAD

**Issue by nataliasitko** [kyma-project/busola#2925]
**Description**

TWs would like to update the texts in Busola that indicate that there are no resources of a specific type in a cluster. Please check if it's possible to update these texts and let us know how to do this

**Area**

- Kyma dashboard

**Reasons**

- Improve UI

**Attachments**

Example:

<img width="860" alt="Screenshot 2024-05-20 at 13 37 30" src="https://github.com/kyma-project/busola/assets/80401180/5e6a20a9-4e37-4f24-a83b-b1dd29c07abd">

**Comment by pbochynski** [comment]
Can you suggest the right message format, please?
