### ISSUE TITLE
Display labels as collapsible element

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#2940]
**Description**

Labels are displayed in Busola for a number of k8s resources such as Namespaces or Pods. Often there are many labels attached to one object so that user on a list view instead of multiple rows, can see only one or two items and their labels. 

While user may not necesarily be interested in the labels but rather primarily to find appropriate list item, it would be good to make labels as collapsible section displayed only on demand (maybe we could display first 2 labels inline and "..." indicator for more)   

**Attachments**
<img width="619" alt="image" src="https://github.com/kyma-project/busola/assets/69588692/e656e920-6fee-4dd8-9c11-9d1718f32431">

**Comment by mrCherry97** [comment]
Labels are removed from the list view.
