### ISSUE TITLE
Issue with details of module being deleted 

### ISSUE THREAD

**Issue by arturskorupa** [kyma-project/busola#2995]
1. I deleted modules: Connectivity Proxy and Transparent Proxy.
2. Despite view of the modules didn't exist any more, module were presented on the Modules list with Ready state.
3. When clicked on a module, I was lead to the empty page (screen below) and couldn't come back (need to reopen the busola)
4. For some time when I clicked on those modules to display a details, right panel opened but the message was saying module doesnt exist

<img width="1335" alt="image" src="https://github.com/kyma-project/busola/assets/69588692/eed3ddff-8547-4530-99b8-6b6b9a1d9221">

**Remedy**
UI must be more resilient, not to be broken for the time of module deletion. 404 page may be displayed but it must have a link back to the module list. 

+We need to check why module's UI was deleted but the module still presented as Ready on the list (is it something wrong with module deletion process or some caching in UI?)

**Comment by OliwiaGowor** [comment]
The prolonged `Ready` state after deletion is not on our side, this is the information we get from the yaml. Our part is to handle the case when there is no resource details.

**Comment by mrCherry97** [comment]
We need to disable onClick for details view, when module is also in `Error` state, because when I'm adding the eventing for example, for couple seconds/minutes it is in `Error` state and extension for details is not available.
