### ISSUE TITLE
Modules: Add option for default channel in channel dropdown

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#3078]
**Description**
As a user, I want to be able to change the channel for the module, and I need to be able to come back to the default option (channel not presented in the YAML of the Kyma resource)

**Reasons**
Users need to be able to come back to the default option and have the channel managed by Kyma resource.

**Acceptance Criteria**
- [x] Discuss with TWS the naming convention of this option, because "Default" could be confusing for the user @mmitoraj 
- [x] Default option is displayed in dropdown
- [x] Option contains information about the channel which will be applied (Channel from Kyma resource)
- [x] Option contains information about the version of the channel that will be applied 
- [x] In `Add` view by default should be selected Default option
- [x] Adjust the test in the kyma-dashboard to cover this use case - https://github.com/kyma-project/kyma-dashboard/pull/349
- [x] Follow DoD

**Attachments**
<img width="473" alt="image" src="https://github.com/user-attachments/assets/ef48969e-4bc7-4a4a-b1e5-da9a1190500f">

**Comment by mmitoraj** [comment]
> I have a discussion with @mmitoraj, and she will talk with the rest of the TWS and come back with some decisions.

As the channel is defined by the Kyma team, we think that a good name for that could be: "Predefined". For example, **Predefined (Fast v1.1.14)**.
