### ISSUE TITLE
Modules: Information about override channel on the modules list

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#3080]
**Description**
As a user, I want to see on the list which channel is overridden from the Kyma CR.

**Reasons**
Users need to be informed which module has overridden the channel.

**Acceptance Criteria**
- [x] Discuss with TWS the naming convention for marking the overridden channel - @mmitoraj 
- [x] One the list is information about the overridden channel
- [ ] Adjust the test in the kyma-dashboard to cover this use case
- [x] Follow DoD

**Attachments**
![image](https://github.com/user-attachments/assets/8cfbe981-2e5a-4e4f-8ff1-953c62aea809)
![image](https://github.com/user-attachments/assets/ff165b02-167b-4f49-a3fd-7d6e526d78dc)

**Comment by mrCherry97** [comment]
I have a discussion with @mmitoraj, and she will talk with the rest of the TWS and come back with some decisions.

**Comment by mmitoraj** [comment]
> I have a discussion with @mmitoraj, and she will talk with the rest of the TWS and come back with some decisions.

"(overridden)" sounds like a good description. We are all ok to keep it as it is.
