### ISSUE TITLE
Introduce i18n Translation into busola

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#321]
**Description**

Busola needs to have translation system integrated and aligned with SAP Product Standards.

**Acceptance Criterias**

- [x] Translation is part of the codebase
- [x] Translation files are in friendly format that can be edited by translators and technical writers

**Comment by Sawthis** [comment]
https://github.com/kyma-project/busola/pull/298
https://github.com/kyma-project/busola/pull/315
https://github.com/kyma-project/busola/pull/325
https://github.com/kyma-project/busola/pull/327
https://github.com/kyma-project/busola/pull/328
https://github.com/kyma-project/busola/pull/334
https://github.com/kyma-project/busola/pull/344

**Comment by Sawthis** [comment]
https://github.com/kyma-project/busola/pull/351
https://github.com/kyma-project/busola/pull/361
https://github.com/kyma-project/busola/pull/368
