### ISSUE TITLE
The browser tab for the Busola dashboard is consuming 100% cpu after sometime of leaving it open

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#3296]
**Description**
The browser tab for the Busola dashboard is consuming 100% cpu after sometime of leaving it open

**Expected result**

**Actual result**

**Steps to reproduce**
(1) log in to the Kyma dashboard and navigate to any page,
(2) put the computer to sleep for >1h,
(3) observe that the tab navigates to https://dashboard.kyma.cloud.sap/clusters and CPU consumption increases to 100%.

**Troubleshooting**

**Comment by mrCherry97** [comment]
there is probably problem with polling when the backend is throwing error, need to add error to this if: https://github.com/kyma-project/busola/blob/main/src/shared/hooks/BackendAPI/useGet.js#L103
need to try to fix the silentRefetch function

**Comment by finally-fancy** [comment]
I have observed the same issue. It appears that in the event of an error, the `clearInterval(intervalId);` function is not called, leading to the continuous creation of interval functions. This continues until all resources are exhausted.
