### ISSUE TITLE
Open redirect vulnerability in dashboard

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#3355]
**Description**

If you click on the following link you will get redirected to sap.com (or an arbitrary phishing page):
https://dashboard.stage.kyma.cloud.sap//sap.com

CVSS 3.1 Low
https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N

**Comment by mrCherry97** [comment]
One more example of the bug: https://dashboard.stage.kyma.cloud.sap//www.youtube.com/watch?v=dQw4w9WgXcQ

when there are `/clusters` or whatever our validation is working correctly, but when someone provides just a link to some phishing page or whatever after the domain, it is automatically redirected to the page after double slashes.
