### ISSUE TITLE
Add possibility to easily manage unmanaged module

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/busola#3357]
**Description**

Now if a module is configured as unmanaged on the Kyma CR level, it's not possible to turn it managed without editing raw yaml. 
The following screenshot shows an unmanaged serverless module:

<img width="2709" alt="Screenshot 2024-09-23 at 13 44 52" src="https://github.com/user-attachments/assets/5d84fec1-7f10-45ae-99df-8531d62fa0d0">

The `Edit` view should have checkbox for every module to easily enable/disable management of every module. Now it looks like this:

<img width="1811" alt="Screenshot 2024-09-23 at 13 46 07" src="https://github.com/user-attachments/assets/4d33d6ed-6393-41f4-8414-c8fe62b2170a">

**Comment by janmedrek** [comment]
Hey @pPrecel, from KLM's perspective the re-managing of modules is not yet supported, this is rather one-way story until we implement this ticket: https://github.com/kyma-project/lifecycle-manager/issues/1667

**Comment by mrCherry97** [comment]
Hi @pPrecel 
We need to make a few adjustments to the editing modules flow.

Acceptance criteria:
- [ ] add checkbox/switch in Edit view managed/unmanaged 
- [ ] add warning when the user is trying to save manage to unmanaged change
- [ ] add information when the user is trying to save unmanaged to manage change
- [ ] contact flow with the UXes and decide if we need to use a checkbox or switch
