### ISSUE TITLE
Decoded secret values have capitalised first letter

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#3359]
**Description**
The secret value should not be modified (capitalised). Secret values are usually case-sensitive. Changing the first letter is not acceptable.

<img width="320" alt="Screenshot 2024-09-24 at 10 54 02" src="https://github.com/user-attachments/assets/c4c238d7-4613-43bb-8655-17c43f8f84fa">

**Comment by dbadura** [comment]
Probably the same issue: https://github.com/kyma-project/busola/issues/3356

**Comment by dbadura** [comment]
Fixed
