### ISSUE TITLE
Resources shown as non existing

### ISSUE THREAD

**Issue by panayotmarinov** [kyma-project/busola#3366]
**Description**

In the Safari browser, when attempting to click on an existing resource such as a namespace, an Istio custom resource, or a transparent proxy custom resource, an error occurs stating: "Such {resource} doesn't exist." This issue does not appear in Google Chrome.

- Using macOS Sonoma 14.6.1.
- The Safari version is 17.6 (19618.3.11.11.5).
- The Chrome version is 129.0.6668.60 (arm64).
- kubectl version response:

```
% kubectl version                                                                                       
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8
```

- The cluster is on stage with id c-051e152.

**Expected result**
The selected resource's details should be displayed.

**Actual result**
An error message appears indicating that the resource does not exist.

**Steps to reproduce**
1. Open the Busola dashboard
2. Click on a specific namespace.

or 

1. Open the Busola dashboard
2. Select "All Namespaces."
3.  Navigate to Kyma -> Istio -> Open the Istio resource named "default."

I am attaching screenshots which illustrate the problem.
![Screenshot 2024-09-27 at 11 40 45](https://github.com/user-attachments/assets/191b61fc-5920-48e7-9627-12f5abc87060)
![Screenshot 2024-09-27 at 11 40 54](https://github.com/user-attachments/assets/047bd58b-31d3-4c63-9ebf-3769a0432ce1)

**Comment by chriskari** [comment]
This issue probably results from the same bug as #3411 and was fixed by 
https://github.com/kyma-project/busola/pull/3425

**Comment by mrCherry97** [comment]
Hi @panayotmarinov 
As Christian wrote, this issue has been fixed by another PR. Please double-check that everything is working fine. If the problem appears again, please reopen the issue or catch us up.

Best regards,
Wisniewski Mateusz
