### ISSUE TITLE
Managing back an unmanaged module should not trigger the warnings, should it?

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#3545]
**Description**

I unmanaged a module earlier and I want to have it manages again.
When changing the toggle back to true, I see warnings that IMO should be visible only when transitioning from managed to unmanaged. 

**Actual result**

![Screenshot 2024-12-18 at 09 11 19](https://github.com/user-attachments/assets/75f47420-f449-4626-a23f-66a8ef175f76)
![Screenshot 2024-12-18 at 09 11 24](https://github.com/user-attachments/assets/5879f3a6-02b0-4cf1-b6fe-8bd9f86e659c)

**Comment by mrCherry97** [comment]
hi @kwiatekus 
there was a decision, that we display this warning all the time, to inform not so advanced users that changing this option could cause some problems, so it should display.
