### ISSUE TITLE
Use natural language for CR names in the Busola UI

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/busola#362]
**Description**

Currently, the UI spells the CR's name `API Rule`, but Kyma documentation uses the `APIRule` spelling pattern that's compliant with the spelling of other Custom Resources. 
This needs to be unified.
~It was decided to change `API Rule` to `APIRule` in the UI.~
Following a discussion on this issue, It was decided to **use natural language for Custom Resource names in the Busola UI**.

**Area**

* Busola/Kyma Dashboard
* Documentation

**Reasons**

Documentation describes steps in Busola and the naming is not consistent.
The naming in the UI and the documentation must be consistent.

**Assignees**

@kyma-project/technical-writers

**Attachments**

![image](https://user-images.githubusercontent.com/53601578/130956870-a40f6d49-8eb2-4e80-8d7f-755749857288.png)

![image](https://user-images.githubusercontent.com/53601578/130956920-e3f1e53e-d3a8-422f-b037-fc61a13a6207.png)

**Related issue**
- https://github.com/kyma-project/kyma/issues/12473
- https://github.com/kyma-project/community/issues/600

**Comment by majakurcius** [comment]
Apart from `APIRule`, there's also `ReplicaSets`, and possibly other CRs with inconsistent spelling that should be corrected.

**Comment by valentinvieriu** [comment]
I don't think we should go this Way. Sometimes the names of the CR are not explicit enough.
