### ISSUE TITLE
Stuck in a loop when no callback URL is provided in the kubeconfig

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/busola#382]
**Description**

When a kubeconfig without a valid callback URL (for auth provider) is uploaded as the only one, Busola will repeatedly try to connect into the cluster, resulting in a loop that makes it unusable.

**Expected result**

There should be a possibility to not connect to a specific cluster by default.

**Actual result**

When accessing Busola it connects to the first available cluster by default. If no callback URL is provided in the kubeconfig it will repeatedly fail.

It automatically redirects to the auth provider and fails:
<img width="864" alt="Screen Shot 2021-09-02 at 10 51 52" src="https://user-images.githubusercontent.com/22869996/131813875-0b5d0460-5242-4c05-a049-db63eeeb7931.png">

**Steps to reproduce**

1. Upload kubeconfig with auth configured and no callback URL
2. Try to access Busola

**Troubleshooting**

The only solution is to wipe the local cache or use the incognito mode.

**Comment by valentinvieriu** [comment]
We know about this issue, and for now we recommend to remove that cluster by going to [https://dashboard.example.com/reset](https://dashboard.example.com/reset). This will avoid that loop, and allow you to delete the cluster and try again
