### ISSUE TITLE
Read value from file replaces key name from preset with file name

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#401]
**Description**

When you create a new secret with a preset you will start with a list of keys. But if you read the value for the key from the file, the key name is replaced with a file name.

**Expected result**
The key name stays as it was defined in the preset

**Actual result**

Key name is equal to file name

**Steps to reproduce**

Create new secret with preset GoogleCloud DNS, switch to Advanced mode, go to 'serviceaccount.json' key and read the value from file. When the file is loaded the file name will replace the key name.

**Comment by voiverine** [comment]
I couldn't reproduce this issue. The filename pops in only when there's no key name

**Comment by pbochynski** [comment]
Yes - it is fixed now.
