### ISSUE TITLE
Node CPU utilisation (percentage) shows wrong values

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#420]
**Description**

Local busola shows extremely high cpu utilisation

**Expected result**

CLI and UI should show the same cpu utilisation

**Actual result**

Value form CLI

```
kubectl top nodes
NAME                CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
k3d-kyma-agent-0    323m         8%     2062Mi          25%
k3d-kyma-server-0   684m         17%    3691Mi          46%
```

Value seen in busola
( ~10100% )

![Screen Shot 2021-09-23 at 10 30 40](https://user-images.githubusercontent.com/6783567/134477288-896aee09-f1c9-419a-85d6-63b03060a5c5.png)

**Steps to reproduce**
Follow instructions from [quick install](https://github.com/kyma-project/kyma/blob/kyma-2.0-docu/docs/02-get-started/01-quick-install.md) guide:

1. Install local kyma instance
```
kyma provision k3d
kyma alpha deploy
```
2. Start local busola 
3. Go to cluster overview page

**Comment by voiverine** [comment]
Busola displays the received data correctly, the error must be somewhere in the k3d
