### ISSUE TITLE
Busola running locally should use default kubeconfig

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/busola#436]
**Description**
I would like to use my default kubeconfig with busola running locally (docker mode). 

**Reasons**
It is natural for developers that K8s tools use the current kubeconfig automatically.
I don't want to upload anything or have additional tools to construct some query parameters. It should be standard command to mount kubeconfig file as a volume in the docker and use all the contexts from it automatically.

**Comment by valentinvieriu** [comment]
we are doing this right now. The `kyma deploy` command passes the kubeconfig id to busola
