### ISSUE TITLE
Dropdown to select a secret should be searchable

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/busola#510]
**Description**
When we maintain an environment variable in the function from the secret, there is a dropdown to select a secret.
Currently, it is just a dropdown. And we need to scroll a long list to find the required secret. It would be great if it can be a searchable dropdown.

**Reasons**

If the namespace has many secrets (for different reasons), it's difficult to find the right one.

**Attachments**
![image](https://user-images.githubusercontent.com/4543139/140439720-1fca314a-1c0b-4291-a15c-d5449435bb96.png)

**Comment by Sawthis** [comment]
Fixed in: https://github.com/kyma-project/busola/pull/520 pull request.
