### ISSUE TITLE
NODE_ENV is used incorrectly

### ISSUE THREAD

**Issue by shorim** [kyma-project/busola#565]
**Description**
Currently the `busola` container generates extensive logs when `NODE_ENV` is set to `production` and only error logs are generated when `NODE_ENV` is set to `development`. However, this is not the conventional way of doing it. It should be the opposite:
`development` --> extensive logs
`production` --> less logs (only error logs)

Note that after this change, the `dashboard` command in the `Kyma CLI` should be slightly modified to reflect this change: https://github.com/kyma-project/cli/blob/main/cmd/kyma/dashboard/cmd.go#L81

**Reasons**
The current approach is confusing. It is against the convention.

**Comment by Sawthis** [comment]
@shorim What convention are you talking about? We want to have more logs on production from backend to have better possibility to debug issues in the future. We don't need these logs during local development.

**Comment by shorim** [comment]
You can check the convention here for example in the Node official docs: https://nodejs.dev/learn/nodejs-the-difference-between-development-and-production
