### ISSUE TITLE
Remove the apiGroups Features from the config map.

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#588]
**Description**

Simplify the busola-config config map. We should add only the necessary overwrites, the rest should be added in the documentation.

Acceptance Criterias:
- `resources/web/configmap.yaml` is changed to reflect this
- `management-plane` config maps are changed to reflect the same strategy 

**Reasons**

The default apiGroups Features like those mentioned above should be documented, but shouldn't be stored in the config map to not confuse the user. If the user wants to overwrite it, he/she can still do it in the config map, but it shouldn't be there by default.
 
Store the data in the code, and override it by the config map. 

**Attachments**

**Comment by Wawrzyn321** [comment]
PR for `management-plane` https://github.tools.sap/kyma/management-plane-config
