### ISSUE TITLE
Press esc in empty role field and it will change to undefine

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#604]
**Description**

**Expected result**
If you press `esc` instead of searching in Create Cluster Role Binding modal value will change to `undefine`.

**Actual result**
Don't set `undefine`.

**Steps to reproduce**
- Open Create Cluster Role Binding modal. 
- Click on the Role dropdown (on input, not arrow)
- Press `esc`.

**Troubleshooting**

**Comment by dariadomagala** [comment]
Could not reproduce
