### ISSUE TITLE
You can select any value in dropdown Create Cluster Role

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#606]
**Description**
APIGroups, Resources and Verbs can be changed to any string. 
If you go to yaml tab you can see that this value has been set.
When you go back to simple/advanced tab the field will we empty.

It might be common for other ComboboxArrayInput dropdowns

**Expected result**
Discuss with the team what solution is better:
- Don't allow to set value that is not in the options list
- Display value even if it is not on the list

**Actual result**

**Steps to reproduce**
-open Create Cluster Role modal
- start searching in APIGroups, Resources or Verbs field
- go to YAML and back
- field is empty

**Troubleshooting**

**Comment by Wawrzyn321** [comment]
It's not reproducible anymore. We were thinking of disallowing the freetype values in APIGroups and Resources, but in the end we decided to keep it - we don't want to show blank `Dropdown` if kubectl-created role brings in unexpected value.
