### ISSUE TITLE
Editing a resource using a yaml section doesn't enable the 'update' button

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#617]
**Description**

If a user wants to edit a resource using the `yaml` tab in the edit modal, the update button will be disabled. They have to edit anything in the `simple`/`advanced` views, to enable it.

Edit: it's in the namespaces view

**Expected result**

Users should be able to edit a resource in any of the views.

**Actual result**

Users cannot adit a resource using only the `yaml` tab.

**Steps to reproduce**

**Troubleshooting**

**Comment by Lyczeq** [comment]
`Update` button is able to click even if nothing has been edited. The issue is out-of-date.
