### ISSUE TITLE
Add tooltips for all statuses like running or provision

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#660]
Add tooltips for all statuses. Make sure

**Acceptance Criteria**

- [ ] Follow Project DOD
- [ ] Add common.tooltips.{status_name} for all statusses

**Comment by akucharska** [comment]
#620

**Comment by Wawrzyn321** [comment]
Please remember about authentication type on Repositories.

**Comment by mrCherry97** [comment]
Please remember about Custom Resource Definitions (SERVED, STORAGE)
