### ISSUE TITLE
Save Function button is too low in Firefox

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/busola#667]
**Description**

Using kyma dashboard command of Kyma 2.0.0-rc8.

![Screenshot 2021-12-03 at 09 12 18](https://user-images.githubusercontent.com/74361703/144612210-5a947aa5-5977-4f27-86d8-d8a3c47b36b5.png)

**Steps to reproduce**

curl -Lo kyma https://storage.googleapis.com/kyma-cli-stable/kyma-darwin
chmod +x kyma
kyma provision k3d
kyma deploy -s 2.0.0-rc8
kyma dashboard

open localhost:3001 in FireFox and use kubeconfig from k3d cluster (k3d kubeconfig write kyma)

**Comment by Wawrzyn321** [comment]
On Chrome too!
