### ISSUE TITLE
Move resources folder out of repository

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#682]
**Description**

Have a separate repo for Busola configuration.

**Reasons**

- Auto bumping the images to hash commits - no PR conflicts for images anymore.
- To have separation between open source and manage offering configuration.

**Tasks**

- Create a new repository in `kyma-project`
- Move `resources` dir from `busola` to new repo
- Adjust prow pipelines for Busola
- Have a bot to bump the images on `busola` merge to main
- Inform SRE to update their bot (so it pulls from the new repo, not from Busola).
- Add GH Actions for promoting Busola to stage and from stage to production.

**Comment by Wawrzyn321** [comment]
Target repo: https://github.com/kyma-project/charts

**Comment by Sawthis** [comment]
The repository will be extended with Kyma Helm charts if our experiment with Busola will succeeds.

**Comment by Sawthis** [comment]
Please remember also about Github releases.
https://github.com/kyma-project/community/blob/main/docs/guidelines/releases-guidelines/06-release-subscription.md
