### ISSUE TITLE
SPIKE: Introduce caching mechanism

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#700]
**Description**

Since we are hammering the apiserver all the time, why don't we try to find a method to cache the responses?

**Reasons**

- In some quarters, hitting the server dozens of times per second is considered impolite.
- Additional benefit - we don't always need (for repeating GETs) to show error message (at least when the first request succeeded - [Using the Fetch API we can edit the response coming from the server, determining if the server is not reachable and providing a response from the cache instead](https://flaviocopes.com/service-workers/)). It would possibly solve #694 

**How?**

With Web Workers / Service Worker, of course! They have shiny [CacheAPI](https://developer.mozilla.org/en-US/docs/Web/API/Cache). I'd suggest to have a stab and find out if it's usable, and of course verify if apiserver accepts the caching deal.

**MORE**

Each k8s call for a list of resources returns a `resourceVersion`, that changes when any of listed resources changes. What if we keep a cache of previously fetched resources, and send a request with the latest observed `resourceVersion`? Does the k8s apiserver respect that and - in case the list didn't change - returns 304 status, or - if list did change - only a diff and the freshest `resourceVersion`? That would be very helpful for the bandwidth - of course, we would need to make 2 calls anyway.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#list-pod-v1-core > Query Parameters > resourceVersion - worth checking out

We could even keep all resources data for a specific cluster in a browser cache (either IndexedDB, LokiJS or anything else). We would display the data from DB, and in the background refetch the freshest one.

**EVEN MORE**

The other idea is to restrict the number of data returned by the list calls - after initial call, remember `resourceVersion` and during next refetch specify `fieldSelector` to `metadata`. THe k8s would return only `{metadata: {resourceVersion: ...}}` instead of the entire list, that would save bandwidth. We could compare next version with the original one and make additional call if they are different.

This is not as good as the solution before, as we would need to make 2 calls - sometimes. It calls for verification when 2 calls _sometimes_ are better than 1 call _always_ (as we have right now).

**Comment by valentinvieriu** [comment]
is this a solution for https://github.com/kyma-project/busola/issues/694 ?

**Comment by Wawrzyn321** [comment]
Bruh

**Comment by Wawrzyn321** [comment]
We introduced a cache for core and core-ui, but we've ditched it for:
* security reasons - we shouldn't persist vulnerable data (Secrets, ConfigMaps) in a storage available in the browser
* unstability of `resourceVersion` - it changes all the time (for some resources), so cache wouldn't help as much.

Findings are kept on #1279 branch, we could reuse them for #1258
