### ISSUE TITLE
SPIKE: Research Extensibility options and extensibility strategy for Busola

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#705]
**Description**

Research and document a technical solution that allows Busola to be easily extended by other teams and projects. A good target for the exploration would be to be able to extract all Kyma components as external ones, and be able to release Busola without them being part of the codebase.

Security Requirements:
We need to be sensitive with our app context. Code running in the app context have access to very sensitive informations.

Nice to have: 
Plugins can extend certain sections of the app to be extended. Example : Preferences, Deployments Detail Page ( or any other section )

**Reasons**

As Busola plans on being a universal K8s dashboard, we need to offer a way to allow custom UI implementations and extensions for projects that have special needs to extend Busola.
Specific custom implementation for Kyma, is embedded in Busola codebase, and might be irrelevant for non Kyma K8s Clusters.

**Attachments**

- https://github.com/backstage/backstage
- https://github.com/dapr/dapr and https://github.com/dapr/components-contrib
- https://github.com/Paciolan/remote-component
- https://www.npmjs.com/package/@shopify/react-import-remote
- Check Lens implementation

**Comment by Sawthis** [comment]
Estimated effort: 5 days for 2 people = 10MD

**Comment by Wawrzyn321** [comment]
https://github.com/kyma-project/busola/pull/732

**Comment by Sawthis** [comment]
Spike was done.
