### ISSUE TITLE
Statuses are inconsistent

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#709]
**Description**

We're not consistent when it comes to the statuses.
* for some resources, like Stateful Sets, we display the status in a form of `running pods / expected pods` (for example `1/4`)
* for Replica Sets, we display the status either as `Error` what means that not all pods are running, or `Running` what means all pods are running
* for Deployments, we show both statuses mentioned above

Additionally, the Deployment details page doesn't have a status, and the Replica Set details page has a different status than the list.

**Expected result**

We should use one approach and be consistent. 

**Actual result**

Statuses are inconsistent

**Steps to reproduce**

**Troubleshooting**

**Comment by valentinvieriu** [comment]
This is covered by https://github.com/kyma-project/busola/issues/620
