### ISSUE TITLE
Busola allows to edit Applications (External systems) in Managed Kyma Runtime  

### ISSUE THREAD

**Issue by koala7659** [kyma-project/busola#712]
**Description**

Busola allows user to Create / Delete and Connect Application representing external systems in Kyma.
This is a standard feature of Kyma Open Source but it should not be the case for Managed Kyma Runtime (SKR). 
In SKR mode applications are created and managed centrally with Kyma Management Plane and propagated to subscribed runtimes with a help of `Compass Runtime Agent` service. User should not be able to modify them at the level of Kyma Runtime.

**Expected result**

Following UI operations for Applications managed by the Runtime Agent should not be possible in Busola:
- Delete Application
- Connect Application 

On SKR clusters there should also be no possibility to use the `Connect Application` button

**Actual result**

Busola allows to: 

- Modify existing Compass application.
- Delete existing Compass application.
- Start procedure to generate connection token for existing application. The procedure fails since it is not possible to generate token in managed Kyma Runtime. After clicking the button `Connect Application` the dialog pops up and does not contain any valid token value.

**Steps to reproduce**

1. Provision Kyma 2.0 as SKR from BTP (using preview plan)
2. Open Busola
3. Observe UI controls that allows to edit applications. You can also enter the application and try to generate token for connection.

**Comment by valentinvieriu** [comment]
@janmedrek We do have the option to mark some resources as protected. We do this with other Kyma resources.
![image](https://user-images.githubusercontent.com/478866/145936182-b04b0bd7-f73e-45c0-ab2a-6ebaa64ee5bf.png)

What would be a selection of labels or annotations ( or something else ) that will allow us to protect those resources

**Comment by valentinvieriu** [comment]
@janmedrek please provide some labels/annotations so we can detect that this is a protected resource

**Comment by janmedrek** [comment]
@valentinvieriu the label for protected resources will be introduced here: https://github.com/kyma-project/kyma/issues/12871

**Comment by janmedrek** [comment]
Regarding the `Connect Application` button we will introduce a Config Map so that it can be disabled cluster-wide.

**Comment by valentinvieriu** [comment]
@janmedrek please come back to this issue when that config map is added.
TY

**Comment by franpog859** [comment]
The configmap is added - https://github.tools.sap/kyma/backlog/issues/2167#issuecomment-532133

**Comment by franpog859** [comment]
The app labeling is added - https://github.com/kyma-project/kyma/issues/12871#issuecomment-998572279
