### ISSUE TITLE
Busola Breaks when pagination exceeds 500 pages

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#721]
**Description**

Busola slows down and breaks when pagination exceeds 500 pages. It seems that the pagination is done on the frontend side and not at API level

**Expected result**

Busola should support any number of pages

**Actual result**

Busola Breaks when 

**Steps to reproduce**

**Troubleshooting**

**Comment by valentinvieriu** [comment]
It seems that we the pagination is not real, we download the whole payload, and this slows down considerably k8s API server when big numbers are involved.
![image](https://user-images.githubusercontent.com/478866/146400137-f68f7055-fbea-414c-bfe9-d401c211d2ec.png)

**Comment by wchrapka** [comment]
There's no option to proceed with a server-side pagination:
- K8 REST API supports only a CLI-style pagination by requesting a next batch of resources (with a combination of the 'limit' and 'continue' GET parameters). 
- It also doesn't allow for querying for resources, which name contains string like 'busola'. Only exact matches are supported with "fieldSelector". So search would not be possible without getting the resources first
- if the continue token is used to receive the next batch of resources, the received results will be cached. I haven't investigated how persistant that cache is. But probably a new initial request would have to be sent

**Comment by valentinvieriu** [comment]
We will close this for now as a known issue with non immediate solution for now
