### ISSUE TITLE
On Token refresh, the current navigation path is lost

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#722]
**Description**

On Token refresh, the current navigation path is lost and you are returned to Cluster Overview

**Expected result**

I would expect that after token refresh, I will return to my previous navigation point

**Actual result**

I'm redirected to Overview Page

**Steps to reproduce**

- wait for token to expire or use a short token
- see that you are redirected to Cluster Overview

**Troubleshooting**

**Comment by Wawrzyn321** [comment]
I can't reproduce it - I've stashed my changes on `wawrzyn321/fix-token-refresh-nav`.

**Comment by Sawthis** [comment]
We couldn't to reproduce this bug.
