### ISSUE TITLE
Fix code scanning alert - Missing rate limiting

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#759]
Tracking issue for:
- [ ] https://github.com/kyma-project/busola/security/code-scanning/1

**Comment by Wawrzyn321** [comment]
bruh

**Comment by valentinvieriu** [comment]
Is this still relevant?

**Comment by Wawrzyn321** [comment]
Turns out it was never relevant - we could use `express-rate-limit` (as suggested [here](https://codeql.github.com/codeql-query-help/javascript/js-missing-rate-limiting/)), but there's no point since this issue only occurs for a Docker Busola. There will be only one user here, it makes no sense to introduce rate limiting then.
