### ISSUE TITLE
Cluster interaction toggles

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#768]
**Description**
Values of the toggles are from before the change.
Changing the values of toggles and go to the `Interface`, then go back to the `Cluster Interaction`. 

**Expected result**
Values have to be updated.

**Actual result**
Change the values of toggles and go to the `Interface`, then go back to the `Cluster Interaction`. 

**Steps to reproduce**

**Troubleshooting**

**Comment by Lyczeq** [comment]
The topic needs to be discussed with the Luigi team. It seems that after toggling the value of the specific feature it is not updated. Method `LuigiClient.getActiveFeatureToggles()` returns the array of the feature toggles but it includes the old one despite the change.
The branch with debugging every step: https://github.com/Lyczeq/busola/tree/bug/cluster-interactions

**Comment by JohannesDoberer** [comment]
Hello,
when you change the Luigi config settings like unset a feature toggle, it is needed to trigger [`Luigi.configChanged()`](https://docs.luigi-project.io/docs/luigi-core-api/?section=configchanged).
The MF received the updated context and the feature toggles list should be up-to-date.
