### ISSUE TITLE
Mark wrong inputs in Subscriptions

### ISSUE THREAD

**Issue by mrCherry97** [kyma-project/busola#774]
**Description**
As a user, I want to know where I made a mistake in creating or editing form for Subscription.

**Reasons**
Fields with wrong data aren't marked. The user has to be informed where he made a mistake.

**Acceptance Criteria**
- [ ] Validation for all fields
- [ ] Fields with wrong input is marked on red
- [ ] Error Message should be displayed under the field - use fundamental method

We should validate the inputs in the way they're validated on the backend. The following links might be very helpful: 
- https://github.com/kyma-project/kyma/blob/95e0208f3536003cec82877049b16416bcc92671/components/eventing-controller/pkg/handlers/nats.go#L279
- https://github.com/kyma-project/kyma/blob/95e0208f3536003cec82877049b16416bcc92671/components/eventing-controller/pkg/handlers/eventtype/clean.go#L46
- https://github.com/kyma-project/kyma/blob/95e0208f3536003cec82877049b16416bcc92671/components/eventing-controller/pkg/handlers/eventtype/parse.go#L13
- https://github.com/kyma-project/kyma/blob/95e0208f3536003cec82877049b16416bcc92671/components/eventing-controller/pkg/handlers/eventtype/clean.go#L15

**Comment by Lyczeq** [comment]
We should validate the inputs in the way they're validated on the backend. The following links might be very helpful: 
- https://github.com/kyma-project/kyma/blob/95e0208f3536003cec82877049b16416bcc92671/components/eventing-controller/pkg/handlers/nats.go#L279
- https://github.com/kyma-project/kyma/blob/95e0208f3536003cec82877049b16416bcc92671/components/eventing-controller/pkg/handlers/eventtype/clean.go#L46
- https://github.com/kyma-project/kyma/blob/95e0208f3536003cec82877049b16416bcc92671/components/eventing-controller/pkg/handlers/eventtype/parse.go#L13
- https://github.com/kyma-project/kyma/blob/95e0208f3536003cec82877049b16416bcc92671/components/eventing-controller/pkg/handlers/eventtype/clean.go#L15
