### ISSUE TITLE
Create Subscription dialog creates invalid event type

### ISSUE THREAD

**Issue by koala7659** [kyma-project/busola#807]
**Description**

When user wants to receive some events from External System (application) in a lambda function - he creates subscription for events with `Create Subscription` dialog. This dialog generates subscription resource for the lambda with `EventType` entry for that requires to receive specific event. The name of `EventType` by default contains literally the name of the application that events are sourced from.  

Unfortunately to send correctly events to target lambda the `Kyma eventing` module requires that `EventType` value for a subscription does not contain any non alphanumeric character. More information of that can be found [here](https://kyma-project.io/docs/kyma/latest/05-technical-reference/evnt-01-event-names) 

There are no such restrictions on names of external system (applications) synchronised with SKR. They can contain dashes. Additionally every application that is synchronised from compass always contains ` mp-` prefix.  So we have guarantee that SKR users will always create invalid subscriptions with UI and will never receive any event in their lambdas.

Kyma version: SKR 2.0.2
Kyma Dashboard Version: 60d51d9

**Expected result**

Subscription created by the Create Subscription Dialog should not contain `EventType` name with any characters (like `- `) that will make them, not working with eventing service. The dialog should also validate and normalise source application name in the way that generated `EventType` becomes automatically compatible with `Kyma Eventing`.

**Actual result**

Subscription created by the Dialog contains `EventType` value with concatenated name of the external system (eg `-` ) that will make this subscription not working with eventing service. 
For example `sap.kyma.custom.mp-frog-ec-202.customer.created.v1` 

**Steps to reproduce**

1. Synchronise External System with SKR
2. Create Lambda, Create subscription for some events with Dialog
3. Try to send Events from External system and receive them in subscribed labdda 

**Troubleshooting**

To fix invalid subscription generated with the Dialog, user can edit yaml file for a subscription and remove all not allowed characters. For example change from `sap.kyma.custom.mp-frog-ec-202.customer.created.v1` to  `sap.kyma.custom.mpfrogec202.customer.created.v1`

**Comment by valentinvieriu** [comment]
We can do the sanitisation in UI, but the backend should reject the wrong EventType. People can use kubectl, or other UI's so change those resources, so I think the backend should reject such items
@k15r

**Comment by valentinvieriu** [comment]
As there is a quite advanced sanitisation logic on the backend, and there is no way to share this configuration with Frontend, we switched on allowing the call to fail, if and allow the backend own the sanitisation / error handeling

**Comment by janmedrek** [comment]
Caused by: https://github.com/kyma-project/kyma/issues/11704
