### ISSUE TITLE
Cannot delete binding managed by BTP operator

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/busola#831]
**Description**

After manually creating a Service Instance and then a Service Binding, there's a warning in the details of my binding, saying that the resource is protected and I cannot modify it:

<img width="1670" alt="Screen Shot 2022-01-20 at 15 13 07" src="https://user-images.githubusercontent.com/35192450/150355106-7474f7a0-95cb-4b6f-9c61-d19ffa43e03e.png">

**Expected result**

Since I'm the one who manually created this resource, I'd like to have an option to delete it as well. 

**Actual result**

There's a warning saying that the resource is protected and I cannot modify it.

**Troubleshooting**

As the warning message says, I can go to Preferences and disable resource protection, but the resource should not be labeled as protected to begin with.

**Comment by wchrapka** [comment]
We ublocked default edition of the resources with present ownerReferences.
