### ISSUE TITLE
Disable old Catalog's readonly mode

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/busola#832]
**Description**

When BTP_CATALOG feature is enabled, we render old Catalog in readonly mode - we should disable this functionality, at least for now (while keeping BTP_CATALOG feature on).

**Comment by valentinvieriu** [comment]
@PK85 please confirm what the behaviour should be here

**Comment by PK85** [comment]
@valentinvieriu for now just disable that read_only when btp-operator resources are present. Please make it configurable, and when time comes to migrate I will ask u to enable that back.

**Comment by valentinvieriu** [comment]
@PK85 we will disable this, but please create another issue explaining what does it mean to be configurable and when we should put it in read only ( would you have special config map set in the cluster ?)
