### ISSUE TITLE
[SPIKE] Implement OIDC login flow in Cypress

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/busola#835]
**Description**

Implement OIDC login flow in Cypress - steps with technical user login. 
OIDC login page doesn't load in Cypress(white page).
[If statement for OIDC flow.](https://github.com/Sawthis/busola/commit/f705ad63e0abdeb2311d2dc46c9eec11f8459df6)

**Reasons**

It's blocker for running automated Cypress tests on SKRs.

**Comment by wchrapka** [comment]
It is possible to login through OIDC programmatically with the use of cy.request as in [this case](https://docs.cypress.io/guides/testing-strategies/auth0-authentication#Custom-Command-for-Auth0-Authentication), if we need it for some reason.

It is impossible to create a standard test of the OIDC flow. Cypress disallows redirections or visiting more than one domain within a test.
