### ISSUE TITLE
Have a short cut to open logs of pod and namespace directly in grafana

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/busola#837]
**Description**
The Kyma dashboard provides a nice functionality to view logs of any container via the apiserver. That is meant to be a quick view on recent logs without any advanced search or aggregation capabilities.

A kyma cluster comes with built-in Grafana being integrated with Loki. Here, you can do more advanced queries over a longer history and cobined for whole pods or namespaces. It will be great if a deep link to the logs in grafana can be provided for any workload and namespace.

In case you have not exposed grafana, maybe the button can be disabled with a popup indicating why?

The old Kyma console had a link on a namespace overview with that deep link: `https://grafana.my-domain/explore?left=["now-1h","now","Loki",{"expr":"{namespace=\"my-namespace\"}"}]`
<img width="992" alt="Screenshot 2022-01-21 at 10 29 26" src="https://user-images.githubusercontent.com/7479371/150503305-84d01957-a144-4a0b-afa9-8667daf43293.png">

The same could be done for the pod overview page using a link like `https://grafana.my-domain/explore?left=["now-1h","now","Loki",{"expr":"{pod=\"my-pod\"}"}]`

**Reasons**
Convenience

**Attachments**

**Comment by valentinvieriu** [comment]
Acceptance Criteria

- [ ] The Deep Link to Grafana is has the same feature toggle as the Observability menu on Cluster Overview
- [ ] We offer the deep link only, we don't check if the Grafana is deployed using the [documentation](https://kyma-project.io/docs/kyma/latest/04-operation-guides/security/sec-06-access-expose-kiali-grafana/)
- [ ] The link is present at the landing page for logs- as an alternative to see logs in Grafana - next to save to a file
