### ISSUE TITLE
Deletion of env variables doesn't have a confirmation modal

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#847]
**Description**

Deletion of env variables doesn't have a confirmation modal, deletes it right away.

**Expected result**

Every deletion should be previously approved by the user (if the user has an option to have a confirmation enabled).

**Actual result**

Env variables are deleted right after clicking the delete icon.

**Steps to reproduce**

**Troubleshooting**

**Comment by mrCherry97** [comment]
Resolved in #875
