### ISSUE TITLE
User experience improvement when choosing a preset

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/busola#860]
**Description**

As a user, I would like to see what kind of preset is selected when I've chosen one. When I want to create a namespace and choose a preset of the `Resource quotas` I need to choose one of the options in the `Select a Preset` dropdown but after a click, I am not sure if I have checked it properly until I click on the `Apply total memory quotas` header to show the whole section. My proposal is to display the selected preset instead of the text `Select a Preset` in the dropdown e.g. `S (limits: 1.5, requests: 1.4Gi)`. When none preset hasn't been selected it should stay the same. When I want to provide custom values of the `Memory limits` or `Memory requests` the text in the dropdown should be `Select a Preset`. 
What is more, when the checkbox is checked it could be nice to open the related section.

**Reasons**

It will improve the user experience when choosing a preset.

**Attachments**
### Current situation:

![image](https://user-images.githubusercontent.com/56163767/150809720-8a085590-7f45-425a-be09-df2e48e76343.png)
 
### Proposed one:

![image](https://user-images.githubusercontent.com/56163767/150810030-9cb412e1-cbbc-406b-8a1a-4af88f119b31.png)

**Comment by valentinvieriu** [comment]
The moment you Change any settings the preset selection is not valid anymore. You can alter the data in such way that technically becomes the value of another preset.
We have a more general issue with preset selection and will be solved holistically for the entire application.
I will close this for now.
