### ISSUE TITLE
Error with rout on cluster connected with kubeconfigID 

### ISSUE THREAD

**Issue by akucharska** [kyma-project/busola#882]
**Description**
Error 'Could not find the requested route'

**Expected result**

**Actual result**

**Steps to reproduce**

- Connect cluster with kubeconfigID
- Go to namespaced
- Add kubeconfigID with different cluster 
- The new cluster is added but... An error is shown during rerouting 

<img width="1680" alt="Screen Shot 2022-01-26 at 10 59 07" src="https://user-images.githubusercontent.com/20790348/151154560-0dbd9b45-c48a-4bb3-a375-f32efd2b1896.png">

**Troubleshooting**

**Comment by valentinvieriu** [comment]
This is an edge-case that it's hard to cover. We will not fix this edgecase
