### ISSUE TITLE
SPIKE: Research if possible to extract prometheus metrics in Busola UI

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#888]
Would be a great feature to be able to extract Metrics from Prometheus while on detail page of various resources like: Pods, Deployments.
Kubernetes offers the possibility too directly access a service [manually-constructing-apiserver-proxy-urls](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls)

It is possible to access the prometheus using a link like [prometheus-query](https://dashboard.dev.kyma.cloud.sap/backend/api/v1/namespaces/kyma-system/services/monitoring-prometheus:web/proxy/api/v1/query?query=node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace="kyma-system", pod="monitoring-grafana-f845ff56b-wgkfb", container="grafana"}&start=1643285741.626&end=1643289341.626&step=14)

Expected Results for SPIKE:

- extract the historical CPU info for pod detail and embed it on the pod detail page.

**Comment by Sawthis** [comment]
Spike is finished. Task for implementation will be created by @valentinvieriu.

**Comment by Sawthis** [comment]
Estimate: 1 PD
