### ISSUE TITLE
Create a namespace with Busola on nkyma cluster for tests

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#893]
Create a namespace with Busola on the `nkyma` cluster instead of creating a new cluster for the e2e tests.

We should use an already existing `nkyma` cluster to deploy Busola, to speed up the testing process.

We can create a new namespace with a specific PR number at the very beginning of the job (and if such namespace already exists, delete the previous one, to avoid conflicts). Then deploy all the resources needed for Busola to work, using the script that we already have in the Busola repository.
Clean up the namespace at the end of the job.

**Comment by Sawthis** [comment]
It's not worth to do it.
