### ISSUE TITLE
Hide the proper fields in the 'hide read-only fields' mode in the editor

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/busola#899]
**Description**

In the 'hide read-only fields' mode, we should hide the `managedFields` and `status` fields, nothing more. Currently, we're hiding the `managedFields` (which is good) and `sidecar.istio.io/status` annotation field if it exists (which is not good), but we don't hide `status` (which is also not good).

**Expected result**

Hide the `managedFields` and `status` fields in the 'hide read-only fields' mode.

- [x] Hide `managedFields`
- [ ] Hide `status`
- [ ] Don't hide the `sidecar.istio.io/status` annotation

**Actual result**

We hide the `sidecar.istio.io/status` annotation field, yet we don't hide `status`.

**Steps to reproduce**

To see the `sidecar.istio.io/status` hiding, check the pods edit view.

**Troubleshooting**

**Comment by akucharska** [comment]
Fixed in https://github.com/kyma-project/busola/pull/916/
