### ISSUE TITLE
Fix linter checks

### ISSUE THREAD

**Issue by grego952** [kyma-project/busola#910]
**Description**

Sometimes linter after `git push` command messes up two lines in the en.yaml file

Before the command:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/62639546/152343511-b595c5cf-9a16-40b5-8cdd-bef030eda4c8.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/62639546/152343590-2f94a635-eeb2-4e22-80de-044a9f6f86b6.png">

After the command:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/62639546/152343671-4e413525-2b00-4cf6-a83c-62e071a3e1f7.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/62639546/152343703-40c0d641-a185-42f9-9062-20d97a77f8a1.png">

**Expected result**

The lines should always start and end with double quotation marks

**Actual result**

The lines start and end with single quotation marks which messes up the en.yaml file and the tests.

**Steps to reproduce**

**Troubleshooting**

**Comment by Lyczeq** [comment]
The root cause of that bug is probably the `yaml-sort` package we use. The [issue](https://github.com/ddebin/yaml-sort/issues/5) has been reported and we need to wait for the fix.

**Comment by majakurcius** [comment]
Reopening as the proposed solution did not work.

**Comment by ddebin** [comment]
Please use the new `--quotingStyle` option, as mentioned here https://github.com/ddebin/yaml-sort/issues/5.
