### ISSUE TITLE
Editing a cluster that has OIDC config does not pre-fill the OIDC data

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#942]
**Description**

Editing a cluster that has OIDC config does not pre-fill the OIDC data

**Expected result**

The OIDC data should be used from the YAML

**Actual result**

The OIDC fields are empty

**Steps to reproduce**

**Troubleshooting**

![image](https://user-images.githubusercontent.com/478866/153207760-171809d6-cc86-4d09-b5a6-873e3d83dd73.png)

**Comment by wchrapka** [comment]
It has been fixed in #917
