### ISSUE TITLE
Why Back to Namespaces and no Back to Cluster Overview

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#944]
When We do deeper in a cluster, we see the menu Back to Namespaces.

That feels wrong, as you are getting back to Cluster Overview

![image](https://user-images.githubusercontent.com/478866/153209986-990442fd-6c27-4b4f-a70f-c1c6205ad4ff.png)

**Comment by dariadomagala** [comment]
You are getting to the list of namespaces, not the cluster overview page, so `back to cluster overview` also feels wrong here.
