### ISSUE TITLE
Adjust the default values of serverless runtime presets in the Kyma Dashboard

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/busola#961]
**Description**

Adjust memory and cpu time of serverless runtime presets in the kyma dashboard

**Reasons**

Small presets have proven to be too small
https://github.com/kyma-project/kyma/issues/12849#issuecomment-1026760912

**Attachments**

[target values](https://github.com/kyma-project/kyma/blob/main/resources/serverless/charts/webhook/values.yaml#L104
)

**Comment by mrCherry97** [comment]
We are getting these informations from config-map, so it's not a topic for us and that changes are not released in 2.0.4 which is the newest release, if changes will be in the new release we can attach them just to `helpers` and `config.js` in busola.

**Comment by valentinvieriu** [comment]
@mrCherry97 can you please mention what config-map needs to be updated?

**Comment by mrCherry97** [comment]
Oh yeah, I forgot, config-map: `serverless-webhook-envs`
