### ISSUE TITLE
Introduce Lighthouse Regression Testing in our Pipeline

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#982]
**Description**

We need to protect our App against performance regressions.

Acceptance Criteria

- [x] We reject all PR that harm in a negative way ( deviation of < 3% ) the lighthouse score from the current status quo

**Reasons**

**Attachments**

[headless-chrome](https://github.com/GoogleChrome/lighthouse/blob/master/docs/headless-chrome.md)

**Comment by Sawthis** [comment]
I think we should try to introduce https://github.com/GoogleChrome/lighthouse-ci especially if we have problems with integration with Cypress. @Wawrzyn321 @qbalukom what do you think?

**Comment by qbalukom** [comment]
If there's a way of reliably logging into a cluster... then sure

**Comment by Wawrzyn321** [comment]
Then let's try this https://www.npmjs.com/package/playwright-lighthouse

**Comment by Wawrzyn321** [comment]
There's no additional iframe, so it'll be an advantage. We can add our code to pick the kubeconfig and then run Lighthouse audit.
