### ISSUE TITLE
Improve Lighthouse score for Cluster Overview

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#984]
**Description**

Acceptance Criteria

- [x] Lighthouse Score is <90 for our Cluster Overview page. The Target is 100% if possible.
- [x]  Follow the Recommended Performance Improvements
- [ ] Identify The slow Pages of our app that are <95

**Reasons**

**Attachments**

![image](https://user-images.githubusercontent.com/478866/154927257-60c2a204-c9e7-449f-a34c-bf718c0645a5.png)

**Comment by Wawrzyn321** [comment]
IDEAS:
Next steps with first load optimisations:

- check out how Nginx can cache resources
- see if chained requests (luigi.css -> *.woff) can be removed
- consider using React.lazy in `/shared`
- further analyze bundle size using `webpack-bundle-analyzer`
