### ISSUE TITLE
SPIKE: Have a Visual Way to display the connected resources

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/busola#986]
Acceptance Criteria
- [x] We research if there is a universal way to detect related / connected resources
- [x] We evaluate if this can be represented in a Visual Way - see https://reactflow.dev/ as an option
- [x] We identify and document some of the shortcomings

Relevant Projects for inspiration:

- https://www.npmjs.com/package/k8s-dot-graph
- https://github.com/benc-uk/kubeview
- https://github.com/ahmetb/kubectl-tree
- https://github.com/viralpoetry/kubesurveyor
- https://github.com/steveteuber/kubectl-graph
- https://github.com/alcideio/rbac-tool

Examples:
![image](https://user-images.githubusercontent.com/478866/154930955-5a850e74-e146-4e04-aadb-8d7593b20081.png)
![image](https://user-images.githubusercontent.com/478866/154931100-ab600240-b5c1-4899-96ad-30d9b7d4c6e2.png)
![image](https://user-images.githubusercontent.com/478866/156114541-5e94b0c1-acd0-455a-b327-f9b95c7cff6b.png)
![image](https://user-images.githubusercontent.com/478866/156114624-4a5600fb-7437-4a8e-88c5-7f24116068fd.png)
![image](https://user-images.githubusercontent.com/478866/156114824-974818b0-94d8-49bb-b7f9-cf0bfd0587e8.png)
![image](https://user-images.githubusercontent.com/478866/156114905-d18c0405-c76d-4ec4-b7de-82c296d72d49.png)

**Comment by Wawrzyn321** [comment]
https://www.npmjs.com/package/vivagraphjs

**Comment by Sawthis** [comment]
Estimation: 3 PD

**Comment by Wawrzyn321** [comment]
Looking at [Lens Resource Map](https://github.com/nevalla/lens-resource-map-extension), there's no nice and easy way for matching resources - for example [here](https://github.com/nevalla/lens-resource-map-extension/blob/master/components/KubeForceChart.tsx#L485), Pod's Secrets are matched manually. Maybe we should create a set of connections/selectors ourselves, like:
```
{
	"selector": "$.spec.template.container.env.valueFrom.secretKeyRef.name",
	"type": "api/secrets"
	"namespaced, allow multiple, etc"...
}
```

**Comment by Wawrzyn321** [comment]
https://github.com/ahmetb/kubectl-tree
