### ISSUE TITLE
Some of the error messages include additional unnecessary information

### ISSUE THREAD

**Issue by grego952** [kyma-project/busola#987]
**Description**
Some of the error messages include additional info that is unnecessary. For example:
<img width="1462" alt="Zrzut ekranu 2022-02-21 o 10 41 22" src="https://user-images.githubusercontent.com/62639546/154930332-f6cdd949-b360-4fb6-b9fb-7e1dc3ea3e0c.png">
It is enough to mention once that something has failed

<img width="1472" alt="Zrzut ekranu 2022-02-21 o 10 42 33" src="https://user-images.githubusercontent.com/62639546/154930941-e0809427-46c9-4443-bb01-80fe86beb7e6.png">
This message is unnecessarily long. Only the last sentence brings some value.

**Expected result**
Error messages should be refactored.

**Actual result**
Error messages include unnecessary repetitions and additional information.

**Steps to reproduce**

**Troubleshooting**

**Comment by klaudiagrz** [comment]
Please remember that good practice in case of an error message is to include info on how the user can fix the problem.

**Comment by grego952** [comment]
Due to the fact that each time errors coming from backend have a different structure, for now the issue is impossible to resolve.
