### ISSUE TITLE
Information that helps user complete the task should not be kept in a tooltip

### ISSUE THREAD

**Issue by grego952** [kyma-project/busola#994]
**Description**
According to [Fiori design guidelines for using tooltips](https://experience.sap.com/internal/fiori-design-web/using-tooltips/#do-not-use-a-tooltip-if), tooltips should not be used if you want to offer an explanation or provide help. This type of information should be visible all the time for the user. It helps them to complete the task. 
Therefore, the following information:
<img width="1180" alt="Zrzut ekranu 2022-02-22 o 07 39 37" src="https://user-images.githubusercontent.com/62639546/155076939-bd1cceee-7346-4db2-af7b-172a1ba4cdd8.png">
should be visible for the user all the time and not only when they hover over a tooltip. It can be placed below the label or when user starts typing in the input form a placeholder tooltip pops up.

**Expected result**
Important information that helps users complete their task should be visible all the time. 

**Actual result**
Users see the important information only when they hover over the tooltip.

**Steps to reproduce**

**Troubleshooting**

**Comment by valentinvieriu** [comment]
@grego952 Do you have any UI recommendation how to do this?
In absence of an alternative, we will stick with current implementation

**Comment by grego952** [comment]
@valentinvieriu We can do it the same as we have in the **Create Cron Job** view. The information that you can specify ranges, multiple values etc. is visible all the time for the user. In my opinion this approach would be perfectly fine.
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/62639546/168223121-bea102a9-6681-449c-87d5-48903b2dc491.png">
